### ISSUE TITLE
Ripple/Highlight effect on a rounded Button does not respect border radius

### ISSUE THREAD

**Issue by Mexxerio** [GeekyAnts/NativeBase#1206]
## react-native, react and native-base version
react-native 0.47.2
react 16.0.0-alpha.12
native-base 2.3.1

but also happens on KitchenSink

## Expected behaviour
When you click a rounded Button the Ripple effect should respect the border radius and stay inside of the button

## Actual behaviour
The Ripple effect does not have a border radius and gives the impression of a rectangular button

## Steps to reproduce (code snippet or screenshot)
1. Clone KitchenSink
2. Go to the rounded button screen
3. Change the background color to `#4e4d4d`
4. Press button

## Screenshot of emulator/device
![screenshot_1504426031](https://user-images.githubusercontent.com/11925037/30001479-e794acfa-908f-11e7-9393-d0501f61bd78.png)

## Is the bug present in both ios and android or in any one of them?
Just tested in Android

**Comment by cklinx** [comment]
+1 Same problem

**Comment by ferprez** [comment]
+1

**Comment by isaachinman** [comment]
@SupriyaKalghatgi Any idea when this will be released?

**Comment by SupriyaKalghatgi** [comment]
@isaachinman #1528 here is the PR
Some contradictory results across different system while verifying this PR, hence delay

**Comment by isaachinman** [comment]
@SupriyaKalghatgi Okay, great. I see you release this lib pretty often. Can we assume this will be rolled out within a few weeks?

**Comment by SupriyaKalghatgi** [comment]
@isaachinman yes ofcourse

**Comment by kayzenkayzen** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.1)

**Comment by akhilsanker** [comment]
Still facing issue in "native-base": "^2.8.2",

Is there any workaround to solve this?

Thanks

**Comment by SupriyaKalghatgi** [comment]
Thats fixed and working

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Thanks for the reply. Sorry to say I am still facing the issue. Could you please find the attachment?
Please find my versions here:
    "native-base": "^2.8.2",
    "react": "16.6.3",
    "react-native": "0.57.8",

[2019_03_01_12_37_12.mp4.zip](https://github.com/GeekyAnts/NativeBase/files/2918308/2019_03_01_12_37_12.mp4.zip)

Thanks you for your time.

**Comment by SupriyaKalghatgi** [comment]
I would recommend clearing node_modules, lock files, run yarn, clear npm cache before build and then build

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Thanks for the suggestion. I would try it and let you know.

Thanks

**Comment by EhsanSarshar** [comment]
I have the latest version 2.12.1.
but also have the same problem
