### ISSUE TITLE
focus, _root, getRef - missing from typings

### ISSUE THREAD

**Issue by Slessi** [GeekyAnts/NativeBase#1803]
## react-native, react and native-base version
- RN `0.55.2`
- R `16.3.2`
- NB `2.4.2`
## Expected behaviour
Typings present
## Actual behaviour
Typings not present
## Steps to reproduce (code snippet or screenshot)
```jsx
<Input getRef={(input) =>this.passwordInput = input}} />
```

> Type '{ getRef: (input: any) => any; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & Readonly<{ children?: ReactNode; }> & Rea...'.

```ts
function focusPassword(input: Input) {
    input._root.focus();
}
```

> Property '_root' does not exist on type 'Input'.

As a result of above `focus()` is also missing I think but I'm not sure. I see it defined in `NativeMethodsMixinStatic` but doesn't *seem* as if that's being referenced anywhere
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Yes
## Any other additional info which would help us debug the issue quicker.

Can be temporarily fixed by adding below typings file to project (`focus` only actually exists on the value of `_root` but I don't know what its meant to be, so I set it to `Input`)
```ts
declare module "native-base" {
    // getRef, _root, focus all missing
    namespace NativeBase {
        interface Input {
            focus?: () => void;
            _root?: Input;
            getRef?: (ref: Input) => void;
        }
    }
}
```

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)

**Comment by Slessi** [comment]
@SupriyaKalghatgi Are you sure?

df536f7 introduced `getRef?: React.Ref<ReactNative.TextInput>`

But shouldn't it be `getRef?: (ref: React.Ref<ReactNative.TextInput>) => void`

**Comment by akhil-geekyants** [comment]
@Slessi checked this. It is working fine for me. Attaching a gif

Gif

![floatinglabel](https://user-images.githubusercontent.com/27768184/39693195-da28cbea-5200-11e8-96a2-05c6b4539bd9.gif)

**Comment by Slessi** [comment]
@akhil-geekyants I concede that `getRef` does actually work (had a mistake on my part) but in your gif you've hidden the missing typing errors for `_root` by setting `password` and `username` to `any`

**Comment by Slessi** [comment]
@akhil-geekyants would just like to point out that this still isn't fixed, `_root` remains missing from the types.

**Comment by janekolszak** [comment]
Yes, `_root` is still missing

**Comment by renielDev** [comment]
Im having the same issue. How to resolve this?
