### ISSUE TITLE
Icon problem when using Redux Form with NativeBase

### ISSUE THREAD

**Issue by chawax** [GeekyAnts/NativeBase#1915]
Environment :
- react-native 0.55.3
- react 16.3.1
- native-base 2.4.4 
- redux-form 7.3.0

I am using NativeBase in a Redux Form field and I want to use Icon component to display a red cross when the field has a validation error.

But I have a strange behaviour you can see on this screenshot (tested on iOS simulator) :

![image](https://user-images.githubusercontent.com/5655399/40306009-46ee9dac-5cfd-11e8-94c2-027a5d588543.png)

It tries to display two icons, one OK, one wrong.  

I also have warnings like this one in the console : 

```
Warning: Failed prop type: Invalid prop `name` of value `caption` supplied to `Icon`, expected one of ["ios-add",...
```
So it looks like it tries to display a second Icon with the Redux Field name as name.

Here is the code of my form component :

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { Button,  Content,  Form,  Icon,  Input,  Item,  Label,  Text } from 'native-base'
import { reduxForm, Field } from 'redux-form'

class CompetitionForm extends Component {

  static propTypes = {
    onCancel: PropTypes.func.isRequired,
    onSubmit: PropTypes.func.isRequired,
  }

  _renderInput = ({  input, label, keyboardType, meta: { touched, error, warning } }) => {

    let hasError = false
    if (touched && error !== undefined) {
      hasError = true
    }

    return (
      <Content>
        <Item floatingLabel error={hasError}>
          <Label>{label}</Label>
          <Input {...input} keyboardType={keyboardType} />
          {
            hasError && <Icon name="close-circle" />
          }
        </Item>
        {
          hasError && <Text style={{ color: 'red' }}>{error}</Text>
        }
      </Content>
    )
  }

  render() {
    return (
      <Form>
        <Field
          name="id"
          component={this._renderInput}
          label="id"
          keyboardType="numeric"
        />
        <Field
          name="caption"
          component={this._renderInput}
          label="nom"
        />
        <Field
          name="numberOfTeams"
          component={this._renderInput}
          label="nombre d'équipes"
          keyboardType="numeric"
        />
        <Content padder>
          <Button block onPress={this.props.handleSubmit(this.props.onSubmit)}>
            <Text>Valider</Text>
          </Button>
        </Content>
        <Content padder>
          <Button block light onPress={this.props.onCancel}>
            <Text>Annuler</Text>
          </Button>
        </Content>
      </Form>
    )
  }
}

const validate = (values) => {
  const errors = {}
  if (!values.id) {
    errors.id = 'veuillez saisir un id'
  }
  if (!values.caption) {
    errors.caption = 'veuillez saisir un nom'
  }
  if (!values.numberOfTeams) {
    errors.numberOfTeams = 'veuillez saisir un nombre d\'équipes'
  }
  return errors
}

export default reduxForm({
  form: 'competition',
  validate,
})(CompetitionForm)

```

Is there something I do wrong ? Or is there a bug with either Redux Form or NativeBase Icon component ?

**Comment by SupriyaKalghatgi** [comment]
@chawax NativeBase Icon should not have issues when used with redux form

I could not find the icon names that you tried to render

Can you share the icon names?

**Comment by chawax** [comment]
I use `close-circle` icon and it displays well actually.
But there's a second icon that is rendered, the one with the question point on the screenshot. And it looks like it has the Redux Form field name as name. If you have a look on the warnings, it tries to set icons with `id` and `caption` name, which are the names of my fields. Very strange. It looks like Field redux form component looks for all `name` properties in children and set them with the field name.

**Comment by SupriyaKalghatgi** [comment]
I can find just this line where you are trying to display icon

```
<Icon name="close-circle" />
```

No where else

**Comment by SupriyaKalghatgi** [comment]
you can check https://reactnativeseed.com/

**Comment by chawax** [comment]
@SupriyaKalghatgi Yes, I just add one Icon component in my code, that's why I don't understand why I have twice.

I just noticed that it works well if I remove `floatingLabel` property on my `Item` component ! So it looks like a problem with floating labels ?

**Comment by lpongetti** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)

**Comment by Sourabhd1164** [comment]
Hi @SupriyaKalghatgi 

I see this icon bug is fixed but I'm using custom icons( images ) right next to a floating label and they're not showing up . They do show up when using stackedLabels

It might be a minor fix. Can you please look into this?
Thanks!

**Comment by SupriyaKalghatgi** [comment]
@Sourabhd1164 I cant help with code snippet and output screenshot

**Comment by Sourabhd1164** [comment]
@SupriyaKalghatgi  Here's my code and output screenshot
https://github.com/GeekyAnts/NativeBase/issues/2271

**Comment by vijay-online-bub** [comment]
I still have the issue of **stackedLabel** Icon alignment issue in v2.8.1.

<img width="357" alt="screenshot 2018-11-09 at 3 46 25 am" src="https://user-images.githubusercontent.com/26415230/48230748-159c4400-e3d2-11e8-929b-33d6e94265eb.png">


works fine with floatingLabel

<img width="295" alt="screenshot 2018-11-09 at 3 47 33 am" src="https://user-images.githubusercontent.com/26415230/48230808-45e3e280-e3d2-11e8-8f35-eb882ec7aa40.png">

**Comment by vanskins** [comment]
Hi this bug is still existing today. As I try to create an APK for my app this bug happens.

**Comment by herdiiyan** [comment]
> Hi this bug is still existing today. As I try to create an APK for my app this bug happens.

this event is the same to me, is there a solution?
