### ISSUE TITLE
Header shadow

### ISSUE THREAD

**Issue by userbq201** [GeekyAnts/NativeBase#2284]
native-base - v 2.8.0

header no shadow and elevation not working

**Comment by SupriyaKalghatgi** [comment]
#2275

**Comment by userbq201** [comment]
@SupriyaKalghatgi a lot of backwards incompatible changes. I'll stay on 2.4.2

**Comment by userbq201** [comment]
@SupriyaKalghatgi you dont understand. 
```js
<Header />
```
no shadow

**Comment by SupriyaKalghatgi** [comment]
@userbq201 What do you mean? I dont understand?

**Comment by userbq201** [comment]
@SupriyaKalghatgi header has no shadow

[screen](https://ibb.co/cU2NhK)

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2284#issuecomment-422762371

**Comment by userbq201** [comment]
@SupriyaKalghatgi in v 2.5.1 header has no shadow

**Comment by SupriyaKalghatgi** [comment]
React Native Issue https://github.com/facebook/react-native/issues/19872

**Comment by SupriyaKalghatgi** [comment]
This was React Native issue, which is fixed with its latest release
Verified with react-native 0.57.1, works like charm!

**Comment by userbq201** [comment]
@SupriyaKalghatgi in react-native@0.57.8 shadow not show

**Comment by userbq201** [comment]
@SupriyaKalghatgi  problem in native base, because 
```js
  <View
    style={{ elevation: 3, height: 100, width: '100%', backgroundColor: 'white' }}
  />
```
instead header work

**Comment by userbq201** [comment]
hm i am wrong
problem in onLayout
any ideas ? This not fixed

**Comment by userbq201** [comment]
i fork and remove onLayout

**Comment by MarcoScabbiolo** [comment]
@SupriyaKalghatgi This issue is still happening on `react-native 0.59.5`, `native-base 2.12.0` and it is not a duplicate of the issue u've linked, @userbq201  is right and looks like he came out with a fix to it. Please reopen the issue, steps to reproduce are easy, just assign `shadowX` and `elevation` properties to a `Header ` element.

**Comment by RomuloDevelop** [comment]
I have the same problem on `native-base 2.13.8` and `expo SDK 38`, which use `react-native 0.59`

**Comment by Aladeusi** [comment]
<Header style={{elevation:0}}>

The above works for me
