### ISSUE TITLE
Unable to find ReactNativePropRegistry (0.22.2 and 0.26)

### ISSUE THREAD

**Issue by michshat** [GeekyAnts/NativeBase#24]
This framework looks really good - Thank you!
Trying it now and running into this issue - I had used latest react-native 0.26 (react 15.0.2), also had it downgraded to 0.22.2 (react 0.14.8) - same issue. Any idea?

![image](https://cloud.githubusercontent.com/assets/13825309/15449069/27036f50-1f41-11e6-9746-809b74dc01ec.png)

**Comment by agindre** [comment]
I've got the same issue 👍   
Looking for a solution or a hint to solve this :)

**Comment by agindre** [comment]
I found a workaround by modifying my package.json dependency from `"react-native": "^0.22.2",` to `"react-native": "^0.24",`. After I did `rm -rf node_module && npm install`, I got the ReactNativePropRegistry.js in my node_module/react-native/Librairies/ReactNative and it works.

**Comment by sankhadeeproy007** [comment]
It has been fixed and is available in development branch. Not publishing now as we're planning on adding a few more features for the next release. Pull from the development branch if you need it urgently.

**Comment by icukaegbu** [comment]
Looked through the code at development branch
<img width="796" alt="screen shot 2016-05-23 at 7 40 43 am" src="https://cloud.githubusercontent.com/assets/8110590/15462299/b79d20be-20b9-11e6-869d-41f315bd1a01.png">
The problem is that ReactNativePropRegistry from "react-native/Libraries/ReactNative/ReactNativePropRegistry" does not exist in RN 0.26 and above. 
How can we resolve

**Comment by sankhadeeproy007** [comment]
#27

**Comment by sankhadeeproy007** [comment]
RN 0.26 supported with latest update.

**Comment by maheshiv** [comment]
I am using react-native v0.29 and still facing this issue. What will be the work around for this issue?

**Comment by sankhadeeproy007** [comment]
Which version of react are you using?

**Comment by maheshiv** [comment]
@sankhadeeproy007, I am using React V15.02

**Comment by sankhadeeproy007** [comment]
Can you check the react directory inside node_modules and see if the path exists?

**Comment by maheshiv** [comment]
@sankhadeeproy007,  fixed this issue by clearing the cache and re-installed node-modules

**Comment by andela-engmkwalusimbi** [comment]
Which version of React and React-Native does the latest version of Native-Base support? I have the latest version of RN and R, and I'm facing the same problem.

**Comment by mateusreis** [comment]
same here

**Comment by jaisonveneri** [comment]
+1

**Comment by matthieugayon** [comment]
same here

**Comment by Alappin** [comment]
Issue is occuring again, looks like facebook removed the 'ReactNativePropsRegistry' file from version 15.4.1. It is never a good idea to depend directly on internal libraries used by a framework or calling internal APIs because they can easily change without backwards compatibility.

**Comment by ujwal-setlur** [comment]
I have the same issue. I have

		"native-base": "^0.5.15",
		"react": "~15.4.0-rc.4",
		"react-native": "0.38.0",

I can't even run through the native-base tutorial.

**Comment by rjblopes** [comment]
I have found the same issue. I noticed though that  'ReactNativePropsRegistry' file is still there but in a different path now. Inside 'react-native/libraries' folder, if I recall correctly. Still, no idea how to update all files in native-base that refer to this lib.

**Comment by jaisonveneri** [comment]
I can with follow:

`"native-base": "^0.5.15",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-native": "^0.37.0"
`

**Comment by jeremypeters** [comment]
Same issue

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest release [0.5.18](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.18)

**Comment by thundenilla** [comment]
`"native-base": "0.5.13",
    "react": "15.3.2",
    "react-native": "0.32.0",`


firstly i upgrade these dependency, then i got the error of RCTWebsocket (Android) and unknown module ......Nativebase/button.js. so i just revert back all the version changes to normal. but now im having this 'Unable to find ReactNativePropRegistry '. Someone please!

**Comment by Alappin** [comment]
@thundenilla make sure the versions match up, "native-base: 0.5.15" and below will work with "react: 15.3.2" and below and "react-native: 0.35.0" and below. The possible causes to your issue could be that you are pulling in new version of react or RN whilst having an older version of native-base. Just to be sure, you could nuke everything in the npm cache and clear your node_modules then do a clean npm install. e.g.

<delete project node_modules>
npm cache clean
npm install

Could also help if your dependencies are exact e.g. "react": "15.3.2" instead of "react": "^15.3.2"

**Comment by thundenilla** [comment]
@Alappin so i just update the versions based on your recommendation. but somehow, its still there.

**Comment by SupriyaKalghatgi** [comment]
[#336](https://github.com/GeekyAnts/NativeBase/issues/336)

**Comment by cinder92** [comment]
same issue here with RN 0.45.1

**Comment by davincho** [comment]
@cinder92 Had the same issue (with `2.2.0`) and solved it by upgrading to version `2.3.1` (https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.1)

**Comment by xunxdd** [comment]
not working. "react-native": "^0.47.0", "native-base": "2.3.1",
