### ISSUE TITLE
ActionSheet is not usable as a native method argument in RN 0.58.0

### ISSUE THREAD

**Issue by ggdegreat** [GeekyAnts/NativeBase#2545]
### 
node 10.14.1
npm  6.4.1
react-native 0.58.0
react 16.6.3
native-base 2.8.0
expo none
xcode none

### Expected behaviour

After update to RN 0.58, i expect it just working fine like before. previous RN is 0.57

### Actual behaviour

When calling `ActionSheet.show...` it give an error like in screenshot below:

![actionsheet](https://user-images.githubusercontent.com/7592567/52094573-9dbd6e80-25fa-11e9-8ae9-e0b9d96ce545.jpg)

### Is the bug present in both iOS and Android or in any one of them?

Android. IOS never tested

**Comment by Udbhav12** [comment]
I am getting the exact same error

**Comment by suvenduchhatoi** [comment]
@ggdegreat @Udbhav12 
The issue was due to ```height: this.state.length * 80,``` in https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Actionsheet.js Line 101...
Fixed with ```height: this.state.items.length * 80,``` 
We will update that soon with next release. Thanks...

**Comment by suvenduchhatoi** [comment]
it has been fixed with commit 13413a06907a9901900f4b8c61affbc982f7f5ed

**Comment by hoboman313** [comment]
This is the wrong fix, but you assumed it was correct just because it made the error go away, correct?
I'm going to ignore the fact that declaring styles inline and outside of `StyleSheet.create` is a minor performance issue according to the native-base docs.
Notice the extra space underneath the "Cancel" button in your screenshot. It's there because the height of each ListItem is not actually 80. The actionsheet looked much better before because the height property was broken and did not evaluate to what you changed it to now.

**Comment by bepehr** [comment]
@suvenduchhatoi : Your suggestion cant fix my problem.

**Comment by suvenduchhatoi** [comment]
@bepehr Are you doing a fresh native-base installation after removing node_modules and clearing cache

**Comment by bepehr** [comment]
@suvenduchhatoi  : yes i did this steps
1  . delete node_modules folders
2 . yarn cache clean
3 . yarn
4 . edit /node_modules/native-base/src/basic/ActionSheet.js
5 . react-native run-android

but still got same error

**Comment by bepehr** [comment]
@suvenduchhatoi  : sory my mistake , i have to replace /node_modules/native-base/dist/src/basic/Actionsheet.js and Actionsheet.js.map with your commit files , it fixed now. thank you

**Comment by suvenduchhatoi** [comment]
@hoboman313 The extra space is due to less number of options as Actionsheet items in the example snippet
![screen shot 1440-06-01 at 7 26 41 pm](https://user-images.githubusercontent.com/44160581/52346710-382c1080-2a46-11e9-8d86-7a6fead13640.png)

**Comment by suvenduchhatoi** [comment]
@hoboman313 The extra spaces is due to less number of options as Actionsheet items. If you increase the number of options, and scroll down to the last option, you can see the difference...
![screen shot 1440-06-01 at 7 26 41 pm](https://user-images.githubusercontent.com/44160581/52346977-da4bf880-2a46-11e9-9250-ea186f701614.png)

**Comment by aiyuchen** [comment]
npm was no update!

**Comment by aiyuchen** [comment]
npm update NativeBase 2.11.0, the problem still remain. please update npm source code

**Comment by janpieterz** [comment]
@suvenduchhatoi Any idea on when the new release containing this will be cut?

**Comment by loris42** [comment]
@janpieterz It's has just been [released](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.12.0)

**Comment by janpieterz** [comment]
I saw it yeah, tested and confirmed.

**Comment by NightWarrior** [comment]
Focus on that <<NaN>>, for me that was causing the issue.
