### ISSUE TITLE
Icons is not showing

### ISSUE THREAD

**Issue by nameer94** [GeekyAnts/NativeBase#2806]
Icons is not showing it shows something like this ▯ only.
react-native: 0.60.4
native-base: 2.12.2
I tried `npm install --save react-native-vector-icons` but nothing changed :/

**Comment by dl-husky73** [comment]
same issues with 2.12.3

**Comment by mwq27** [comment]
Same problem with 
```json
    "native-base": "^2.13.0",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-navigation": "2.25.0",
    "styled-components": "^4.3.2"
```
I tried FontAwesome and AntDesign, both just showing the X. I'm running in Android Simulator.

**Comment by hectorthiele** [comment]
Same Issue with:
    "native-base": "^2.12.2",
    "react": "16.8.6",
    "react-native": "0.60.4",`
`

**Comment by nameer94** [comment]
any solution yet!!!???

**Comment by nameer94** [comment]
I found the solution
https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-378546936

just add this code to `app/build.gradle`
`apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

**Comment by kaminaly** [comment]
Same Issue with:
"native-base": "^2.12.2",
"react": "16.8.6",
"react-native": "0.60.4",

I've fixed it with copying fonts manually
[oblador/react-native-vector-icons#661 (comment)](https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-450724142)

**Comment by mwq27** [comment]
@nameer94's solution worked for me.

**Comment by tomchomiak** [comment]
At this moment, auto linking for react-native-vector-icons in react native 0.60 isn't working. You can copy the fonts manually or here's another solution that worked for me:

1.) Uninstall react-native-vector-icons using npm or yarn
```bash
npm uninstall react-native-vector-icons --save
```
2.) cd into your ios folder and rerun pod install
```bash
cd ios
pod install
cd ../
```
3.) Reinstall react-native-vector-icons using npm or yarn and link the icons manually
```bash
npm install react-native-vector-icons --save
react-native link react-native-vector-icons
```
4.) Restart your simulators for good measure and rerun your app
```bash
react-native run-ios
react-native run-android
```

**Comment by PlabanJr** [comment]
Hope [this](https://github.com/GeekyAnts/NativeBase/issues/2806#issuecomment-517905424) resolves the issue. Feel free to create a new issue if the issue persists. Also check out our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).
 
Thank you!

**Comment by r0b0t3d** [comment]
@PlabanJr This issue still persists on `2.13.5`. I think this issue came when you did refactor deprecated lifecycle methods.
In `IconNB.js`
```
componentDidUpdate(nextProps) {
    if (nextProps.type && this.props.type !== nextProps.type) {
      this.setIcon(nextProps.type);
    }
  }
```
should be
```
componentDidUpdate(prevProps) {
    if (prevProps.type && this.props.type !== prevProps.type) {
      this.setIcon(this.props.type);
    }
  }
```

Please correct if I am wrong.

**Comment by khasky** [comment]
I confirm that `react-native-vector-icons` is not working in auto-linking mode for **react-native 0.61.1**.
In addition to @tomchomiak answer, you have to create **react-native.config.js** file with the following content:

```
module.exports = {
  dependencies: {
    'react-native-vector-icons': {
      platforms: {
        android: null
      }
    }
  }
};
```

**Comment by mufaddalhamidofficial** [comment]
@khasky where to create that file??

**Comment by danlupascu** [comment]
@mufaddalhamidofficial In the root folder of your app

**Comment by mufaddalhamidofficial** [comment]
what about expo...
@khasky will this work with expo

**Comment by andresteje** [comment]
>  `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

Its worked for me

**Comment by ramanasak** [comment]
> I found the solution
> [oblador/react-native-vector-icons#661 (comment)](https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-378546936)
> 
> just add this code to `app/build.gradle`
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

this worked for me, Thanks !

**Comment by ajaymarathe9** [comment]
> I found the solution
> [oblador/react-native-vector-icons#661 (comment)](https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-378546936)
> 
> just add this code to `app/build.gradle`
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

It's working Guys. thanks.

**Comment by zanotta** [comment]
> > I found the solution
> > [oblador/react-native-vector-icons#661 (comment)](https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-378546936)
> > just add this code to `app/build.gradle`
> > `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`
> 
> It's working Guys. thanks.

Yep, this solution worked for me.

**Comment by AdrianMrn** [comment]
`apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"` wasn't working for me.

I had to copy all the fonts from `node_modules/native-base/Fonts` to `android/app/src/main/assets/fonts`.

**Comment by Milutin-P** [comment]
Had the same problem with `native-base v2.15.0` and these dependencies
`
    "native-base": "^2.15.0",
    "react": "16.13.1",
    "react-native": "0.63.4",`
       
Adding this code mentioned up there `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"` in android/app/build.gradle solved it!

**Comment by KennedyKeinstein** [comment]
> I found the solution
> [oblador/react-native-vector-icons#661 (comment)](https://github.com/oblador/react-native-vector-icons/issues/661#issuecomment-378546936)
> 
> just add this code to `app/build.gradle`
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

This work for me! Thanks @nameer94

**Comment by DoHue97** [comment]
> react-native-vector-icons

hello, i try this it worked when run debug mode but when i try ./gradlew assembleRelease for get build release apk, the icons not work. Do you know for this?
