### ISSUE TITLE
OnPress not working on Button

### ISSUE THREAD

**Issue by pk936** [GeekyAnts/NativeBase#3224]
```
"native-base": "^2.13.13",
"react": "16.13.1",
"react-native": "^0.63.2",
```

I have 2 buttons on a screen. One inside **Content** and one outside **Content**. The outside button not working.
Even if I remove **Footer** and **FooterTab** still the issue is there.

```
<Container>
        <Content>
            <Button
                danger
                onPress={() => alert()}>

                <Text style={{
                    color: "#fff",
                    fontSize: 15,
                    marginLeft: 5
                }}>
                    WORKING
                </Text>
            </Button>
        </Content>
        <Footer>
            <FooterTab>
                <Button
                    danger
                    onPress={() => alert()}>
                    <Text style={{
                        color: "#fff",
                        fontSize: 15,
                        marginLeft: 5
                    }}>
                        NOT WORKING
                </Text>
                </Button>
            </FooterTab>
        </Footer>
    </Container>
```

![screenshot-2020-08-23_13 42 52 342](https://user-images.githubusercontent.com/28622041/90974240-deffd100-e546-11ea-8c09-daf9e1560b6d.png)

**Comment by chloehjung** [comment]
Is it not working after the toast message is displayed at the bottom of the screen?
If so, your issue is probably related to this bug #3196 
There was a recent release to fix this bug so update it to the latest version and that should fix it.

**Comment by walterholohan** [comment]
Try upgrade to 2.13.14. That version has the fix for this issue.

**Comment by pk936** [comment]
Yes, it worked, after upgrade.

**Comment by monicse09ku** [comment]
Hello, I am using react-native `0.63.3` and native base `2.13.14`. Still facing the problem. Previously I solved it by downgrading to `2.13.8`. But after upgrading my react-native version, it stopped working. Then I have tried `2.13.14`. Is there anything else i should do. 

N.B. yarn was used to install everything.

**Comment by JohnTendik** [comment]
`v2.13.15` has the same issue, button onPress is non-functioning with react-native `0.63.3`

**Comment by monicse09ku** [comment]
For all those people who are still facing the issue, I failed to find a good solution rather a work around. I used a custom component consisting buttons to create a custom footer. Although it is not the perfect solution but it works!!
