### ISSUE TITLE
Android: Custom fonts not rendered with correct font when using fontWeight/fontStyle

### ISSUE THREAD

**Issue by chaaya** [GeekyAnts/NativeBase#3811]
**Describe the bug**
Bold/SemiBold/Italic fonts not working on Android when you are using custom fonts.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a custom font set to NativeBase
2. Render ```<Text fontWeight="bold">Hello world</Text>```
3. The Text gets rendered as the default device system font.
4. See screenshots

**Expected behaviour**
The <Text/> component should render the correct font/font-weight/font-style based on theme configuration.

**Screenshots**
***iOS (working)***
![image](https://user-images.githubusercontent.com/7448249/124925116-6984de00-dffc-11eb-804e-babafc12674c.png)
***Android (not working)***
![image](https://user-images.githubusercontent.com/7448249/124925152-71448280-dffc-11eb-8c50-9d5ad0e125f8.png)

**Platform**
 - Device: Samsung S10
 - OS: Android

**Additional information**
The correct font gets rendered  when I removed the fontWeight and fontStyle prop from <StyledText /> component in the source code. But that might break for users who doesnt have a custom font. My suggestion to the solution is to check if the user has not configured a custom font than add the fontWeight and fontStyle prop to the component internally otherwhise just omit them.

Would be happy to help on this issue and create PR but I am going on vacation now and wont be able to help you out right now.

**Comment by intergalacticspacehighway** [comment]
@chaaya thanks for reporting, this has been fixed in the latest version.

**Comment by ENT108** [comment]
It works only for iOS, Android doesn't respect `fontWeight` prop. Please re-open.

**Comment by facuescobar** [comment]
Same here, please reopen it, font is not rendering correctly on Android

**Comment by olivan94** [comment]
fontWeight prop still not working with custom fonts on Android

**Comment by jimpala** [comment]
Still not working for me either, having to directly reference the name of the fontFamily at desired weight

**Comment by nagydan1** [comment]
Still a problem, please reopen

**Comment by epshtielsl** [comment]
@intergalacticspacehighway I am also seeing this issue in v3.4.20.  Font weights working in iOS but not in Android.

**Comment by minhtamwebmaster** [comment]
Still a problem, please reopen

**Comment by ccdwyer** [comment]
Still seeing this issue as well.

**Comment by cjshearer** [comment]
I'm not seeing this issue directly, although I am noticing responsive resolution of `fontWeight` doesn't work on Android with a custom font configured, so we've added this patch:

```patch
diff --git a/src/components/primitives/Text/index.tsx b/src/components/primitives/Text/index.tsx
index be860aaddd8cd25d335cca035cbcfeabb2b82c01..d9cc0b2e5dbab3f6ea570066315d8c1ddc9243f3 100644
--- a/src/components/primitives/Text/index.tsx
+++ b/src/components/primitives/Text/index.tsx
@@ -36,7 +36,7 @@ const Text = ({ children, ...props }: ITextProps, ref: any) => {
     props,
     {},
     {
-      resolveResponsively: ['noOfLines', 'numberOfLines'],
+      resolveResponsively: ['noOfLines', 'numberOfLines', 'fontWeight'],
       // We override the component base theme if text has an ancestor.
       componentTheme: hasTextAncestor ? {} : undefined,
     }

```

**Comment by eyupdogan** [comment]
Still a problem, please reopen
