### ISSUE TITLE
ForwardRef(creatIcon) in Select is missing the key prop

### ISSUE THREAD

**Issue by YenTingWu** [GeekyAnts/NativeBase#4429]
**Describe the bug**

I copied the example code in the docs, and the warning shows up. I thought it occurred somewhere with `ForwardRef(createdIcon)`, so I removed the `endIcon` in `_selectedItem` and tried again. But the warning was still there.

```jsx
<Select
  minWidth="200"
  accessibilityLabel="Choose Service"
  placeholder="Choose Service"
  _selectedItem={{
    bg: 'teal.600',
    endIcon: <CheckIcon size="5" />,
  }}
  mt="1"
>
  <Select.Item label="UX Research" value="ux" />
  <Select.Item label="Web Development" value="web" />
  <Select.Item label="Cross Platform Development" value="cross" />
  <Select.Item label="UI Designing" value="ui" />
  <Select.Item label="Backend Development" value="backend" />
</Select>
```

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef(createdIcon)`. See https://reactjs.org/link/warning-keys for more information.
G@http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:156206:36
    in createdIcon
    in RCTView (created by View)
    in View
    in Unknown
    in Box
    in InputAdvance
    in Input
    in RCTView (created by View)
    in View
    in RCTView (created by View)
    in View (created by Pressable)
    in Pressable (created by Pressable)
    in RCTView (created by View)
    in View
    in Unknown
    in Box
    in Select
    in RCTView (created by View)
    in View
    in Unknown
    in Box
    in TouchableWithoutFeedback (created by EntryScreen)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView
    in Unknown
    in Unknown (created by EntryScreen)
    in EntryScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in NativeStackNavigator (created by RootNavigator)
    in RootNavigator (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by Navigation)
    in Navigation (created by App)
    in AuthContextProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in QueryClientProvider (created by App)
    in I18nextProvider (created by App)
    in SSRProvider (created by NativeBaseProvider)
    in ToastProvider (created by NativeBaseProvider)
    in PortalProvider (created by NativeBaseProvider)
    in HybridProvider (created by NativeBaseProvider)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by NativeBaseProvider)
    in NativeBaseConfigProviderProvider (created by NativeBaseProvider)
    in ThemeProvider (created by NativeBaseProvider)
    in NativeBaseProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react/cjs/react-jsx-runtime.development.js:117:4 in printWarning
at node_modules/react/cjs/react-jsx-runtime.development.js:93:16 in error
at node_modules/react/cjs/react-jsx-runtime.development.js:986:9 in validateExplicitKey
at node_modules/react/cjs/react-jsx-runtime.development.js:1013:29 in validateChildKeys
at node_modules/react/cjs/react-jsx-runtime.development.js:1184:27 in jsxWithValidation
at node_modules/native-base/src/components/primitives/Icon/createIcon.tsx:14:6 in createdIcon
at node_modules/@react-navigation/native/src/useThenable.tsx:25:13 in resolve
```

**To Reproduce**

Copy the code below and paste it anywhere in your expo app.

```jsx
<Select
  minWidth="200"
  accessibilityLabel="Choose Service"
  placeholder="Choose Service"
  _selectedItem={{
    bg: 'teal.600',
    endIcon: <CheckIcon size="5" />,
  }}
  mt="1"
>
  <Select.Item label="UX Research" value="ux" />
  <Select.Item label="Web Development" value="web" />
  <Select.Item label="Cross Platform Development" value="cross" />
  <Select.Item label="UI Designing" value="ui" />
  <Select.Item label="Backend Development" value="backend" />
</Select>
```

**Expected behaviour**

No warning shows up.

**Screenshots**

<img alt='iphone' src='https://user-images.githubusercontent.com/57777349/146872305-809320b6-32b9-414f-aab4-86d50dc974f7.png' height='700px' /> 

<img alt='nativebase_select_iphone' src='https://user-images.githubusercontent.com/57777349/146872318-5277337e-b50a-4523-a2e5-d89183773ee3.png' height='700px' /> 

**Platform**

- NativeBase version 3.2.2
- Device: iPhone12 (simulator)
- OS: MacOS
- React Native version 0.64.3
- Expo sdk version 44
- node 16.6.2
- yarn 1.22.17

**Additional information**

**Comment by hrithik73** [comment]
Getting the exact same error :)
Any upadare regarding this will be very helpfull

**Comment by OneHatRepo** [comment]
Same issue

**Comment by OneHatRepo** [comment]
The immediate issue is in Select (native-base/src/components/primitives/Select), which is using the ChevronDownIcon (native-base/src/components/primitives/Icon/Icons/Chevron) by default. This icon is created with the createIcon() function (native-base/src/components/primitives/Icon/createIcon). If this function returns an SVGIcon _with a key,_ the error goes away. So a bandaid fix would be to change line 14 of createIcon to:

      <SVGIcon children={children} {...initialProps} {...props} ref={ref} key="mykey" />

However, _this very well might have knock-on affects._ It could be that this key would register as a duplicate/collision where multiple icons were created. So it would be best if someone who knows the internals of NativeBase would change this.

I think it would be great if createIcon could accept a key prop, so the convenience components (e.g. ChevronDownIcon) could each add their own unique key (e.g. "ChevronDownIcon"), which would be unlikely to collide.

**Comment by Ahmed-Ibrahim-Anter** [comment]
Not this problem only I have this issue also slowwwwwwwwwer in two-component [Model&& Select] components  for a test I use picker components  from react-native and suddenly with its performance please solve this problem and also slower in your components

**Comment by OneHatRepo** [comment]
For anyone coming here needing a quick fix: the _Select_ element allows you to submit your own drop down icon using the _dropdownIcon_ prop. Using this instead of the default, and specifying a key for it, should work.

**Comment by surajahmed** [comment]
This issue has been fixed in the latest version (v3.3.1)

**Comment by mchambaud** [comment]
I'm on 3.3.5 and still have this error 🤔

**Comment by DeluxeOwl** [comment]
Same, using the latest version and seeing this error.

**Comment by dlombardi** [comment]
Still seeing this error as well.  Although it looks like the team is aware

**Comment by ankit-tailor** [comment]
Hi Everyone, Thanks for reporting the issue, we are working on it.

**Comment by srinivasarajui** [comment]
Any Update or work around.

**Comment by OneHatRepo** [comment]
Work around is [listed above](https://github.com/GeekyAnts/NativeBase/issues/4429#issuecomment-1002855021).

**Comment by srinivasarajui** [comment]
I feel that the problem is with ChevronDownIcon. If I add this icon I am getting the error. The problem is not with select but with this icon.

**Comment by trip16661** [comment]
I'm also getting the same error while creating custom icons with createdIcon.

**Comment by aliexalter** [comment]
Getting same error, is there any way to provide custom icon ?

**Comment by Zackyist** [comment]
I just got the same error with version 3.3.7:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef(createdIcon)`. See https://reactjs.org/link/warning-keys for more information.
```

I was able to use the workaround suggested by @OneHatRepo to fix it by adding the *dropdownIcon* prop and using a custom icon for all my *Select* elements:

```react
<Select
        ...
        dropdownIcon={
          <Icon
            as={Ionicons}
            name={"chevron-down-sharp"}
            size="5"
            color="darkgray"
            key={
              Math.random()
            }
          />
        }
>
```

(Probably should use a better key value though but this was a quick and dirty fix :smile:)

**Comment by wailinkyaww** [comment]
Getting the same issue. Any update on this?

**Comment by surajahmed** [comment]
Thanks for your patience. We're currently working on a new release with these fixes.

**Comment by wailinkyaww** [comment]
> Thanks for your patience. We're currently working on a new release with these fixes.

Thanks for the update!

**Comment by Viraj-10** [comment]
Hi @wailinkyaww, I am unable to reproduce the issue. Can you provide a snack link? also try using version v3.4.6.

**Comment by dhatGuy** [comment]
https://github.com/GeekyAnts/NativeBase/issues/4543#issuecomment-1021327199 @Viraj-10

**Comment by ankit-tailor** [comment]
Hi everyone, This issue is fixed in `3.4.0`. Let me know if this doesn't work for you.

**Comment by Bubex** [comment]
I don't know if internally it occurs for the same reason, and sorry if not, and if I'm reporting in the wrong place.
But I had this problem when using IconButton nested with ThreeDotsIcon. (in `3.4.9`)

`<IconButton icon={<ThreeDotsIcon />} />`

The results was:

> Warning: Each child in a list should have a unique "key" prop.
> Check the render method of `ForwardRef(createdIcon)`. See https://reactjs.org/link/warning-keys for more information.

**Comment by zoie0312** [comment]
I'm also having this error with ThreeDotsIcon
`<Center size="8" bg="trueGray.200" borderRadius="20">
                <ThreeDotsIcon
                    size="sm"
                    onPress={() => navigation.navigate("WalletDetail")}
                />
            </Center>`
The error msg, 

> Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef(createdIcon)`

**Comment by zxm9988** [comment]
Hey , I fix it like this.
~~~
const BackIcon = () => {
  const CustomIcon = createIcon({
    viewBox: '0 0 36 36',
    path: [
      <Path
        key="backIcon"
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M10 16.4375L8.95453 17.5L1.28092 9.70137C0.89798 9.31219 0.897981 8.68781 1.28092 8.29863L8.95453 0.5L10 1.5625L2.68173 9L10 16.4375Z"
        fill="#121212"
      />,
    ],
  })
  return <CustomIcon name="BackIcon" size={12} />
}



~~~
