### ISSUE TITLE
onChangeText not working on Input

### ISSUE THREAD

**Issue by DimitriMikadze** [GeekyAnts/NativeBase#483]
"react-native": "0.41.1"
"native-base": "^2.0.1"

React Native TextInput has method onChangeText, example:
````
<TextInput
    onChangeText={(text) => {this.setState({text}); }}
    value={this.state.text}
/>
````
From docs Native base Input is React Native's TextInput implementation, but when adding onChangeText to Input it's not working, example:
````
<Input
    onChangeText={(text) => {this.setState({text}); }}
    value={this.state.text}
/>
````
I'm testing it on IOS simulator on Mac OSX El Capitan.

**Comment by sankhadeeproy007** [comment]
Seems to work fine. Please attach a sample of your use case.
![input](https://cloud.githubusercontent.com/assets/10998047/22738694/6de6bb7c-ee2e-11e6-8e02-0085119ce667.gif)

**Comment by NeonXP** [comment]
Have same issue.

Not work:
```
<Item floatingLabel>
    <Input placeholder="Token" onChangeText={console.log} value={this.state.token} />
</Item>
```
Work:
```
<Item>
    <Input placeholder="Token" onChangeText={console.log} value={this.state.token} />
</Item>
```

Difference in **floatingLabel** attribute. I don't know why.

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by DimitriMikadze** [comment]
@sankhadeeproy007 I was testing also with floatingLabel and scenario was exactly same as your uploaded  gif, except it was not logging anything.

**Comment by sankhadeeproy007** [comment]
Yes, it'll be fixed with the next update.

**Comment by peter1a** [comment]
Find one bug also, refs to other component doesn't work:
Here is my code:

`<Form style={ Styles.login_form }>
                                <Item>
                                    <Label>Uporabniško ime</Label>
                                    <Input
                                        autoCapitalize="none"
                                        onChangeText={ (text) => this.setState({ UserName: text }) }
                                        onSubmitEditing={ (event) => {
                                            this.refs.Password.focus();
                                        }}
                                    />
                                </Item>
                                <Item>
                                    <Label>Geslo</Label>
                                    <Input
                                        secureTextEntry={ true }
                                        autoCapitalize="none"
                                        onChangeText={ (text) => this.setState({ Password: text }) }
                                        ref={'Password'}
                                        onSubmitEditing={ (event) => {
                                            this.onPressButton();
                                        }}
                                    />
                                </Item>
                                <Button style={ Styles.login_button } onPress={ () => this.onPressButton() } light block><Text>Prijava</Text></Button>
                            </Form>`

Here is error which i get after press submit button in UserName field:
**undefined is not a function (evaluating '_this3.refs.Password.focus()')**

**Comment by sankhadeeproy007** [comment]
Replace `this.refs.Password.focus();` by `this.refs._root.Password.focus();`

**Comment by peter1a** [comment]
Still same error

**Comment by sankhadeeproy007** [comment]
Is that the case for floating label? Can you try with regular label and check?

**Comment by peter1a** [comment]
Console.log gives my undefined for this.refs._root.

I am using <Input> without floating label just normal input
`<Item inlineLabel>
                                    <Label>Uporabniško ime</Label>
                                    <Input
                                        autoCapitalize="none"
                                        onChangeText={ (text) => this.setState({ UserName: text }) }
                                        onSubmitEditing={ (event) => {
                                            this.refs._root.Password.focus();
                                        }}
                                    />
                                </Item>`

**Comment by shivrajkumar** [comment]
@peter1a Upgade "native-base" to latest version i.e, "2.0.5".
That should solve your issue

**Comment by peter1a** [comment]
Already have: native-base@2.0.5, react@15.4.2, react-native@0.41.2

**Comment by sankhadeeproy007** [comment]
Fixed with v2.0.6

**Comment by peter1a** [comment]
There is still problem with Refs, works perfect when using TextView.

**Comment by Clowning** [comment]
Yes i have the same issue :/ !

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 Reopened because 2 people say that it is not fixed. Let's check this.

**Comment by sankhadeeproy007** [comment]
It's actually a different issue. The one with `refs`.

**Comment by shivrajkumar** [comment]
@peter1a `this.refs.Password._root.focus()` should work

**Comment by peter1a** [comment]
Works, tnx!

**Comment by EdwardNelson** [comment]
Still not working on 2.2.0

**Comment by foufee** [comment]
Second what EdwardNelson said, however with 2.3.0 having the same problem.

**Comment by PineLover** [comment]
can i get the name of tool on the video?, developer's tool .....

**Comment by SupriyaKalghatgi** [comment]
@EdwardNelson Finding same issue yet?

**Comment by SupriyaKalghatgi** [comment]
@PineLover Thats `licecap`

**Comment by akhil-geekyants** [comment]
onChangeText is working fine.

![floatinglabelissue2](https://user-images.githubusercontent.com/27768184/33115563-73d35550-cf87-11e7-9258-6932cf9c7274.gif)

**Comment by karthickeyang** [comment]
hi,
i am new to react native,  when using onChangeText with <Input /> i can able to type, but text not showing in input box.

`<View>
        <Header searchBar rounded>
        <Item>
            <Icon name="ios-search" />
            <Input 
            onChangeText= { term => this.setState({ term })}
            value={this.state.term}
            />
            <Icon name="ios-people" />
          </Item>
          <Left><Button
        onPress={() => console.log(this.state.term)}
          >
            <Text>Search</Text>
          </Button></Left>

        </Header>
      </View>`
