### ISSUE TITLE
variant is not working anymore on Select on version 3.4.1

### ISSUE THREAD

**Issue by goxr3plus** [GeekyAnts/NativeBase#4931]
### What is the bug

I had the following code in v3.3.12 

![image](https://user-images.githubusercontent.com/20374208/163492085-e9c28a1d-f3e6-4000-96b1-301deb16473e.png)

and it produced an unstyled select box  .

Now after just upgrading to 3.4.1 i literally changed nothing from my code completely nothing i just upgraded the dependency 

![image](https://user-images.githubusercontent.com/20374208/163492233-09df4ca7-e10c-4d02-9b29-ffdefa0b2771.png)

i tried all the variant  combinations to check and all just produce this grey box around the Select

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by goxr3plus** [comment]
@surajahmed Heyyy bosss how are you :) , do you know why this happened :) ?

**Comment by ankit-tailor** [comment]
Hi @goxr3plus , Thanks for reporting the issue. We're working on it.

**Comment by goxr3plus** [comment]
@surajahmed  @ankit-tailor  You have changed the way we style the <Select component ? i need to use a new property :) ?

**Comment by simonflk** [comment]
Presumably related... In the documentation under accessibility, it says:

> use `native` variant. Accessibility improvements on styled variant is in-progress.

I am adding `variant="native"` and I still cannot open the select with Voiceover by double-tapping when the select button is focused.

**Comment by haveamission** [comment]
Also not working on <Button /> either

**Comment by goxr3plus** [comment]
@ankit-tailor  Any news on how can we fix that using the latest version of the library :) ?

**Comment by fahad39** [comment]
Kindly resolve this issue

**Comment by punndcoder28** [comment]
Hey guys! We are facing the same issue as well on `v3.4.6`. Looks like variant prop is broken on `<Select />`

**Comment by F7-CalebM** [comment]
Hey everyone, I'm using v3.4.7 and I am noticing this issue as well. None of the variants are working

**Comment by ricohumme** [comment]
Until then I'll stick around on 3.3.12

**Comment by punndcoder28** [comment]
@ankit-tailor Any updates on the fix for this issue?

**Comment by kirgy** [comment]
Also suffering this issue; all theme variants are non-functional above version `3.3.12`, downgrading to `"native-base": "3.3.12"` works around the problem.

**Comment by ankit-tailor** [comment]
Hey everyone, Select variant is fixed in `v3.4.13`. Let me know if it works for you.

**Comment by ricohumme** [comment]
When you say Select variant, is it just the select variant, or all variants which are fixed, like the Text variant case I mentioned?

**Comment by ankit-tailor** [comment]
Other variants are working fine, Can you share snack link or code snippet for Text variant?

**Comment by pors** [comment]
The `Heading` also doesn't work anymore.

**Comment by ricohumme** [comment]
@pors Does is still work for you on 3.3.12 ?

**Comment by Viraj-10** [comment]
Hi @pors,
 ```
Heading: {
        defaultProps: {
          size: 'xl',
        },
        baseStyle: {
          alignSelf: 'flex-start',
          marginTop: '10px',
          marginBottom: '10px',
          fontSize: '32px',
        },
        variants: {
          auth: {
            _light: { color: Colors.charcoalGrey },
            marginLeft: '10px',
          },
          portfolio: {
            _light: { color: Colors.lightGrey },
            marginLeft: '0px',
          },
        },
      },
```
try using above code.

**Comment by pors** [comment]
> Hi @pors,
> 
> ```
> Heading: {
>        defaultProps: {
>          size: 'xl',
>        },
>        baseStyle: {
>          alignSelf: 'flex-start',
>          marginTop: '10px',
>          marginBottom: '10px',
>          fontSize: '32px',
>        },
>        variants: {
>          auth: {
>            _light: { color: Colors.charcoalGrey },
>            marginLeft: '10px',
>          },
>          portfolio: {
>            _light: { color: Colors.lightGrey },
>            marginLeft: '0px',
>          },
>        },
>      },
> ```
> 
> try using above code.

That works, thanks!

**Comment by pors** [comment]
> 

I'm pretty sure it did!

**Comment by Elvin1993** [comment]
change /node_modules/native-base/src/components/primitives/Select/Select.tsx
and add this code can fixed Select variant bug
 variant={props.variant}
```
const commonInput = (
    <Input
      placeholder={placeholder}
      InputRightElement={rightIcon}
      {...resolvedProps}
      // NOTE: Adding ts-ignore as we're not exposing isFocused in the Input component
      // @ts-ignore-next-line
      variant={props.variant} // !!!   add this code , can fixed Select variant bug
      isFocused={isFocused}
      isHovered={isHovered}
      aria-hidden={true}
      importantForAccessibility="no"
      value={selectedItem ? selectedItem.label : ''}
      editable={false}
      focusable={false}
      isDisabled={isDisabled}
      pointerEvents="none"
    />
  );
```

**Comment by ankit-tailor** [comment]
Hi everyone, Thanks for your patience. This issue is fixed in `3.4.15`.

**Comment by pors** [comment]
@ankit-tailor upgrading to 3.4.15 crashes my app for web:

```
useResponsiveQuery.web.ts:2 Uncaught Error: Cannot find module 'react-native-web/dist/exports/StyleSheet/createCompileableStyle'
    at webpackMissingModule (useResponsiveQuery.web.ts:2:1)
    at ./node_modules/native-base/lib/module/utils/useResponsiveQuery/useResponsiveQuery.web.js (useResponsiveQuery.web.ts:2:1)
```

**Comment by ankit-tailor** [comment]
Hey @pors, Do the below steps. We've added a new dependency in `3.4.15`.
1. Delete node_modules
2. yarn install

**Comment by pors** [comment]
> Hey @pors, Do the below steps. We've added a new dependency in `3.4.15`.
> 
> 1. Delete node_modules
> 2. yarn install

Doesn't help :(

**Comment by punndcoder28** [comment]
Using version `3.4.17` and the variant is still broken. @ankit-tailor please reopen this issue or should a new issue be created.
<img width="306" alt="Screenshot 2022-09-29 at 9 58 20 AM" src="https://user-images.githubusercontent.com/32433964/192939114-75e2226b-9ba6-4062-9b36-251b2cda7fdc.png">

Also another bug is with the drop down icon color which does not work as well. Code for the component is something as below. The icon is supposed to be blue but is falling back to red. Is that the default color native base uses when nothing is provided?
```
<Select
              fontSize="md"
              fontWeight={500}
              p="2"
              pl="4"
              variant="underlined"
              borderWidth="1"
              borderColor="gtBlue.500"
              customDropdownIconProps={{
                size: '8',
                p: '2',
                pr: '4',
                color: 'gtBrandBlue',
              }}
              _selectedItem={{
                bg: 'gtBrandBlue',
                borderRadius: 32,
                borderWidth: 1,
                borderColor: 'black',
                _text: {
                  color: 'white',
                  fontWeight: 500,
                },
              }}
              _item={{
                my: 2,
                borderRadius: 32,
                borderWidth: 1,
                borderColor: 'gray.500',
                _text: {
                  fontWeight: 400,
                },
              }}
              selectedValue={value}
              onValueChange={changeLocation}>
```

**Comment by gabrielsmenezes** [comment]
> Using version `3.4.17` and the variant is still broken. @ankit-tailor please reopen this issue or should a new issue be created. <img alt="Screenshot 2022-09-29 at 9 58 20 AM" width="306" src="https://user-images.githubusercontent.com/32433964/192939114-75e2226b-9ba6-4062-9b36-251b2cda7fdc.png">
> 
> Code for the component is something as below.
> 
> ```
> <Select
>               fontSize="md"
>               fontWeight={500}
>               p="2"
>               pl="4"
>               variant="underlined"
>               borderWidth="1"
>               borderColor="gtBlue.500"
>               _selectedItem={{
>                 bg: 'gtBrandBlue',
>                 borderRadius: 32,
>                 borderWidth: 1,
>                 borderColor: 'black',
>                 _text: {
>                   color: 'white',
>                   fontWeight: 500,
>                 },
>               }}
>               _item={{
>                 my: 2,
>                 borderRadius: 32,
>                 borderWidth: 1,
>                 borderColor: 'gray.500',
>                 _text: {
>                   fontWeight: 400,
>                 },
>               }}
>               selectedValue={value}
>               onValueChange={changeLocation}>
> ```
> 
> Edit - A temporary solution I found was to use `variant='unstyled'` and style the borders (or other properties )as needed until `variant` is fixed

I'm using the version 3.4.17 and variant="rounded" is working.
