### ISSUE TITLE
Dynamic List won't refresh when data refreshes

### ISSUE THREAD

**Issue by MengjueW** [GeekyAnts/NativeBase#698]
Hi all,

Recently when doing development using NativeBase I found the List won't rerender when the datasource has changed. My code is like:
"<List dataArray={this.state.items} renderRow={(data) =>"

And then I use this.setState(newItems). The component get rerendered and List doesn't. I read from an existing issue that if the reference of the datasource hasn't changed then it won't rerender. However, the newItems isn't the same reference as the old this.state.items and it's still not working.

Is it a bug? It's definitely very broken since the "dynamic" list isn't really dynamic at all. Hope it could be fixed soon.

**Comment by velicue** [comment]
I found this could be solved if we also use`
`const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
      this.state = {
        dataSource: ds.cloneWithRows(props.dataArray)
}`
in componentWillReceiveProps.
Suggested that you changed to this.

**Comment by shivrajkumar** [comment]
Fixed with v2.1.3

**Comment by EgaSetya** [comment]
I'm facing the same issue on v2.1.3, I tried both using state and props.. and both still causing the issue. How do you guys fix this issue?

**Comment by SupriyaKalghatgi** [comment]
@EgaSetya It can help us to help if if you post your `package.json` and code snippet with log

**Comment by mgit7** [comment]
@EgaSetya  I am having trouble implementing this solution as well.
@SupriyaKalghatgi  Is this how one would implement it? The list doesnt render after the button has been clicked even though the data was changed and setState was called inside the onButtonPress function. I have attached a snippet of the code below and I have also inserted log statements that are located inside the function to output the data and verify it has changed. The log statements show that the data has changed, but looking at the '_dirtyRows' function results being false, it doesnt recognize the change. Do you have any suggestions of what I would be doing wrong?


"dependencies": {
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-elements": "^0.12.2",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.11"

```

class MenuScreen extends Component {

constructor(props) {

super(props);

 

const ds = new ListView.DataSource({rowHasChanged: (row1,row2)
=> row1 !== row2})

var items = [{ id: 0, Flavor: "Cookies n' Cream", Favorite:
'star' }, { id: 1, Flavor: "Cookies", Favorite: 'star-border'
}, {id: 2, Flavor: "Cream", Favorite: 'star' }]

 

this.state = {

data: ds,

ds: items

};




this.checkBoxPressed = this.checkBoxPressed.bind(this)
this.renderRow = this.renderRow.bind(this)
this.onButtonPress = this.onButtonPress.bind(this)

}

checkBoxPressed() {

console.log('pressed')

this.setState({ checked: !this.state.checked })

};


// I am trying to get the buttonPress to update the 'Favorite' icon prop but it seems even though when the new data is set and the state changes, the props do not render at all.

onButtonPress(item) {

var newItems = []; //Create new Array

newItems = this.state.ds.slice() //Copy original array

console.log('Before Setting Favorite Toggle', newItems[item.id])

newItems[item.id].Favorite = item.Favorite === 'star'
? 'star-border' : 'star'; //Change props accordingly

console.log('After Setting Favorite - Verify Change',newItems[item.id])




//Set new data to render 

this.setState({
data: this.state.data.cloneWithRows(newItems)
})

console.log('AFTER SETTING THE STATE WITH NEW DATA - Verify State Data Changed', this.state.data)
};




componentDidMount(){

this.setState({

data: this.state.data.cloneWithRows(this.state.ds),

})

}




renderRow(item) {

console.log(item)

return (

<ListItem iconRight>

<Image source={require('../../../images/menu.jpg')} style={{ width:
35, height: 32, borderRadius: 10 }} />

<Text style={styles.listItemsTextStyle}>{item.Flavor}</Text>

<Right style={{ flexDirection: 'row', justifyContent: 'flex-end',
marginRight: 10 }}>

<FavoriteButton

onButtonPress={() => { this.onButtonPress(item) }}

iconProps={item.Favorite}

/>

<CheckBox onPress={() => this.checkBoxPressed()} style={{
borderColor: 'purple', backgroundColor: 'purple', marginBottom: 5 }} checked={this.state.checked}
/>

</Right>

</ListItem>




)

}




render() {

return (

<Container>

<Content>

<List dataArray={this.state.ds}

renderRow={(item) => this.renderRow(item) }>

 

</List>

</Content>

</Container>

)

}

}
```


06-22 11:41:51.974  6039  6206 I ReactNativeJS: 'Before Setting Favorite Toggle', { id: 1, Flavor: 'Cookies', Favorite: 'star-border' }
06-22 11:41:51.974  6039  6206 I ReactNativeJS: 'After Setting Favorite - Verify Change', { id: 1, Flavor: 'Cookies', Favorite: 'star' }
06-22 11:41:51.975  6039  6206 I ReactNativeJS: 'AFTER SETTING THE STATE WITH NEW DATA - Verify State Data Changed', { _rowHasChanged: [Function: rowHasChanged],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _getRowData: [Function: defaultGetRowData],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _sectionHeaderHasChanged: [Function],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _getSectionHeaderData: [Function: defaultGetSectionHeaderData],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _dataBlob:
06-22 11:41:51.975  6039  6206 I ReactNativeJS:    { s1:
06-22 11:41:51.975  6039  6206 I ReactNativeJS:       [ { id: 0, Flavor: 'Cookies n\' Cream', Favorite: 'star-border' },
06-22 11:41:51.975  6039  6206 I ReactNativeJS:         { id: 1, Flavor: 'Cookies', Favorite: 'star' },
06-22 11:41:51.975  6039  6206 I ReactNativeJS:         { id: 2, Flavor: 'Cream', Favorite: 'star' } ] },
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _dirtyRows: [ [ false, false, false ] ],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _dirtySections: [ false ],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   _cachedRowCount: 3,
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   rowIdentities: [ [ '0', '1', '2' ] ],
06-22 11:41:51.975  6039  6206 I ReactNativeJS:   sectionIdentities: [ 's1' ] }

**Comment by gouravsood** [comment]
It is not fixed yet. I had the same issue where List once rendered, was not updating even if the state of array elements changed.

Implementation which doesn't work:

    <List
      dataArray={this.props.allRecords}
      renderRow={item =>
        <Item key={i}
              onPress={() => this.handleRecordSelection(item)}>
          <Text style={(item.selected) ?
            {fontWeight: 'bold'} : {}}>{item.name}</Text>
        </Item>
    }/> 

Below are my dependencies.

    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "native-base": "2.1.4",

Please re-open this issue.

**Comment by aemdy-revel** [comment]
I'm experiencing the same issue!

**Comment by gouravsood** [comment]
I moved away from NativeBase List and used ReactNative FlatList as documented here:

https://facebook.github.io/react-native/docs/flatlist.html

extraData is the key property to refresh the list with data change.

Good reference:
https://medium.com/react-native-development/how-to-use-the-flatlist-component-react-native-basics-92c482816fe6

**Comment by kingarawana** [comment]
This is not a good long term solution, but might help in the short term. In my case, my list is fairly short. To get the dynamic list to re render, I deep cloned my items reference before using it in <List dataArray={items}...> In my case I just used lodash's cloneDeep method, 'items = _.cloneDeep(items);'. This seems to have solved my issue in the short term until I figure out how to get native base Dynamic List to rerender.

**Comment by ashkonhakimi** [comment]
@kingarawana Finally!! This worked for me. Thanks a lot!!

**Comment by Manzn** [comment]
I had the same issue with the native base List over the last 2 days and just found a solution.

Before updating the data source with setState, clear the data source by using setState({yourSource: []}).
After that it worked for me by simply using setState({yourSource: newSource}).

So from my expericnce/tests, the list doesn´t update if the number elements of the data source stays the same.
If the elements change in numbers, then the list also updates incorrectly. At least when the numbers are decreasing, I think it was the last item in the array got deleted.

**Comment by frapa** [comment]
@Manzn Same here. If I set an empty array and then set the correct one, it works.

**Comment by SupriyaKalghatgi** [comment]
Please use FlatList along with ListItem

**Comment by akhzarna** [comment]
I had the same issue but resolved using extraData = {this.state}

complete Code is here

<FlatList

          style={styles.listView}
          data={this.state.readingArray}
          extraData={this.state}
          renderItem=
          {({item})=>
.............................

**Comment by MrTinyByte** [comment]
Like @gouravsood, I also moved to FlatList, it's so much more reliable than List, and no need to deep clone array

**Comment by SimonVuong** [comment]
works for me as long as I initialize dataArray to an empty list.

good:
```
state = { data = [] } //initialize state to empty list
<List dataArray={this.state.data} renderRow={thing => <Text>{thing}</Text>} />
```

bad:
```
// this.state.data is initially undefined
<List dataArray={this.state.data} renderRow={thing => <Text>{thing}</Text>} />
```

**Comment by amriteshonly4u** [comment]
# this will work ....
1. set the state with blank value
2. then use settimeout


` 
      this.setState({BillList:[]});
      setTimeout(()=>{this.setState({BillList:arr});},0);`

**Comment by thomGeenen** [comment]
I had to change to a flatlist too. Native Base is not always very reliable.

**Comment by magicbacon** [comment]
> # this will work ....
> 1. set the state with blank value
> 2. then use settimeout
> 
> ` this.setState({BillList:[]}); setTimeout(()=>{this.setState({BillList:arr});},0);`

This did work for me.

**Comment by Nrjwolf** [comment]
this solution `this.setState({BillList:[]}); setTimeout(()=>{this.setState({BillList:arr});},0)`; is not good, because you will have visual lag, like a blank area where you have your list. 

Moving to FlatList resolve my problem
