### ISSUE TITLE
Footer animates above keyboard on Android

### ISSUE THREAD

**Issue by fbacker** [GeekyAnts/NativeBase#787]
## react-native, react and native-base version

    "native-base": "2.1.2",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",

## Expected behaviour
When focus TextInput footer should stay down as it does in iOS

## Actual behaviour
Footer animates above keyboard input on android

## Steps to reproduce (code snippet or screenshot)
	<Container>
          <Content>

          <H1>VÄLKOMMEN</H1>

          <Form>

            <Item stackedLabel  >
              <Label>Personnummer</Label>
              <Input keyboardType='numeric'
              returnKeyType='next'
              autoFocus={false}
              autoCorrect={false}
              multiline={false}
              maxLength={13}
             />
            </Item>

            <Item stackedLabel  >
              <Label>Lösenord</Label>
              <Input keyboardType='default'
                returnKeyType='send'
                autoCorrect={false}
                multiline={false}
                secureTextEntry={true}
                 />
            </Item>

          </Form>

          <View style={{width:200, alignSelf:'center',flex:1}}>
            <Button primary full
              disabled={account.isFetching} >
              <Text>LOGGA IN</Text>
            </Button>
          </View>

        </Content>
        <Footer style={{backgroundColor:'transparent',borderTopWidth:0}} >
          <FooterTab style={{backgroundColor:'transparent'}} >
            <View style={styles.footer}>
            
              <Button transparent light small style={{alignSelf:'center'}}
                disabled={account.isFetching}>
                <Text style={{textDecorationLine:'underline'}}>Glömt mitt lösenord</Text>
              </Button>

              <Button transparent light small style={{alignSelf:'center'}}
                disabled={account.isFetching}>
                <Text style={{textDecorationLine:'underline'}}>Registrera dig som ny användare</Text>
              </Button>
              
            </View>
          </FooterTab>

        </Footer>
      </Container>

## Screenshot of emulator/device
iOS | Android
------------ | -------------
<img src="https://fat.gfycat.com/SecondMasculineGuineapig.gif" width="250"> | <img src="https://fat.gfycat.com/ForcefulTinyFrogmouth.gif" width="250">

## Is the bug present in both ios and android or in any one of them?
Android

**Comment by yeknava** [comment]
Its a bug for sure but as a temporary solution i used this code:
```
    constructor(props) {
        super(props);
        this.state = {
            showFooter: true
        }
    }

    componentWillMount () {
        this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow.bind(this));
        this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide.bind(this));
    }

    componentWillUnmount () {
        this.keyboardDidShowListener.remove();
        this.keyboardDidHideListener.remove();
    }
    _keyboardDidShow () {
        this.setState({showFooter: false});
    }

    _keyboardDidHide () {
        this.setState({showFooter: true});
    }
```

**Comment by fbacker** [comment]
thx, that worked.

**Comment by yeknava** [comment]
@fbacker as this issue is still a bug and my solution was hackish, its better to let this issue be open till bug being fix in library.

**Comment by sankhadeeproy007** [comment]
I'm not very sure this is an issue with NativeBase. It has more to with the way android handles the keyboard.

**Comment by manuelkch** [comment]
@fbacker  i fixed it globally with 
`<activity
..............
        android:windowSoftInputMode="stateUnspecified|adjustPan"
-------------
`
in my AndroidManifest.xml

**Comment by fbacker** [comment]
@manuelkch Yaaay, That did the trick.
Closing issue, this is a better solution.

**Comment by fbacker** [comment]
Just a note. This will remove the KeyboardAvoidingView feature.

**Comment by avdept** [comment]
@fbacker Where is this feature being used ?

**Comment by amirmatin** [comment]
this didn't work for me and problem still persists
    android:windowSoftInputMode="stateUnspecified|adjustPan"

**Comment by fbacker** [comment]
@avdept where? Se first post for video showing the issue

**Comment by SupriyaKalghatgi** [comment]
@fbacker @yeknava Do you have expo with this?

**Comment by romildojpaiter** [comment]
Thanks @fbacker, your solution saved my life.

**Comment by tonilxm** [comment]
I think this issue should be stay opened. Solution from  @manuelkch  will make KeyboardAvoidingView stop working in Android and What @yeknava offer is just a work around.
