### ISSUE TITLE
Header alignment

### ISSUE THREAD

**Issue by andrejunges** [GeekyAnts/NativeBase#82]
If I add a `Header` with just one button (left or right) the title isn't centered anymore based on the screen.. Its center based on the "rest width"..

Current behaviour
![image](https://cloud.githubusercontent.com/assets/5039334/17138049/cb2da2ec-5314-11e6-8f33-acf12006ca8c.png)

Expected behaviour (Im using here the same icon and text but with the same background color)
![image](https://cloud.githubusercontent.com/assets/5039334/17138035/bb86cb7a-5314-11e6-9f04-8c473c9758ca.png)

```JSX
<Header>
  <Button transparent>
    <Icon size={30} name="ios-arrow-back" />
    Back
  </Button>
  <Title>Login</Title>
</Header>
```

Am I missing something?

**Comment by zzimbler** [comment]
I experienced this issues as well, my solution was to drop an empty button on the right of the Title... obviously non-ideal but it works.

```Javascript
<Header>
  <Button transparent>
    <Icon size={30} name="ios-arrow-back" />
    Back
  </Button>
  <Title>My Super Cool Title</Title>
  <Button transparent> </Button>
</Header>
```

**Comment by sankhadeeproy007** [comment]
Updated to master. Will publish later this week. Thanks @zzimbler for the quick solution.

**Comment by ErkanSen14** [comment]
Jumping on this, another issue is when you put multiple buttons (more than 2), they all default to the right side and you can't move them anywhere else on the header.

<img width="372" alt="screen shot 2016-07-30 at 12 00 53 am" src="https://cloud.githubusercontent.com/assets/17013914/17268192/c456260c-55e8-11e6-8d2e-6c1d2ded5975.png">

**Comment by sankhadeeproy007** [comment]
@ErkanSen14 I did go through the design guidelines of both Google and Apples, and although it wasn't clearly mentioned any where. All the examples/screenshots had just 1 button to the left of the title and the remaining were aligned to the right. Is there any example anywhere which has more buttons to the left. We'd then look into it.

**Comment by ronaldheft** [comment]
@sanketsahusoft Does this mean the issue is fixed? I don't see it in master or in the most recent release.

**Comment by sankhadeeproy007** [comment]
@ronaldheft Could you please post snippets/screenshots of your code and the resultant UI? Do I need to reopen this?

**Comment by ronaldheft** [comment]
@sankhadeeproy007 My apologies, the issue is indeed fixed. Thanks!

**Comment by btrautmann** [comment]
I am still seeing this issue. I'm new to React Native so that may be an issue, so bear with me:

"native-base": "^2.3.1"

```
<Header>
    <Button transparent onPress={() => Actions.pop()}>
        <Icon size={30} name={this.state.IOS ? 'ios-arrow-back' : 'arrow-back'} />
        <Text>Alerts</Text>
    </Button>
    <Body>
        <Title>Details</Title>
    </Body>
</Header>
```

Results in:

![screen shot 2017-08-07 at 2 26 15 pm](https://user-images.githubusercontent.com/8343465/29040377-c3764a22-7b7c-11e7-9afc-bc41f1bd161f.png)

I would love some help :)

**Comment by sankhadeeproy007** [comment]
```<Header>
    <Button transparent onPress={() => Actions.pop()}>
        <Icon size={30} name={this.state.IOS ? 'ios-arrow-back' : 'arrow-back'} />
        <Text>Alerts</Text>
    </Button>
    <Body>
        <Title>Details</Title>
    </Body>
</Header>
<Right />
```
try this out.
Import `Right` from native-base

**Comment by btrautmann** [comment]
Thanks for the quick response! Unfortunately that helped _slightly_ but it's still not centered.

![screen shot 2017-08-07 at 2 44 49 pm](https://user-images.githubusercontent.com/8343465/29040953-066f83be-7b7f-11e7-9897-f5cca81f62d6.png)

I also tried placing it inside the Header tag but that moved the title over way too much.

![screen shot 2017-08-07 at 2 46 10 pm](https://user-images.githubusercontent.com/8343465/29040996-2c148e8e-7b7f-11e7-85f8-6ef861903cbd.png)

**Comment by sankhadeeproy007** [comment]
Put the Button inside `Left`

**Comment by btrautmann** [comment]
Awesome! That works for iOS.

Do you generally recommend people make different `Header`s for the two platforms? With the same setup above, Android now looks like this:

![screen shot 2017-08-07 at 2 57 36 pm](https://user-images.githubusercontent.com/8343465/29041455-e3f78442-7b80-11e7-8fdf-c9d2bfa5aee4.png)

The title is too far _right_ :(

**Comment by sankhadeeproy007** [comment]
Well that is because the guidelines on Android (material design) suggest that the Header title be slightly aligned to the left.

**Comment by btrautmann** [comment]
Yeah, I know it should be to the left (I'm an Android developer actually, just jumping into RN recently)... But what I'm saying is with native-base, it's too far to the right (towards center). The light blue bar above is from the Messenger app, and it's the standard distance fro left. The native-base (purple) is too far to the right/center.

**Comment by sankhadeeproy007** [comment]
Oh you can always add a negative margin to the title to fix that.

**Comment by btrautmann** [comment]
Gotcha, thanks for your help!

**Comment by lopespm** [comment]
To fix this problem, I applied this style to the `<Left>` component:

    headerLeft: {
        flex: 0,
        paddingLeft: 6,
        width: 62
    }

According to the [material design guidelines](https://material.io/guidelines/layout/structure.html#structure-app-bar), the leftmost icon is spaced 16dp from left, and the title 72dp. Since the `<Header>` already has 10 units of horizontal padding, the resulting `<Left>` padding left is 6 (16-10) and the width of the is 62 (72-10)

This is the result:

![screen shot 2018-01-02 at 18 27 14](https://user-images.githubusercontent.com/3640622/34494939-bb00cd6c-efea-11e7-88a1-7f297092dcd7.png)

**Comment by hjJunior** [comment]
Thanks @lopespm this is realy helpfull :)

**Comment by Arshiamidos** [comment]
i tested this issue with this trick 
worked for me in Android emulator and IOS simulator and real devices(&roid,IOS)
![screen shot - - at](https://user-images.githubusercontent.com/6451804/37338986-53137a7c-26ce-11e8-82bf-4616f420ee14.png)
```
<Header>
  <Left>
    <Button transparent    >
      <Icon name="arrow-back" onPress={() => this.props.navigation.goBack()}/>
    </Button>
  </Left>
  <Body style={{alignItems:'flex-end',backgroundColor:'yellow'}}>
    <Title style={{textAlign:'left',backgroundColor:'red'}}>دیوار</Title>
  </Body>
  <Right>
    <Button transparent onPress={() => this.props.navigation.navigate("DrawerOpen")}>
      <Icon name="menu" />
    </Button>
  </Right>
</Header>
```

**Comment by Arshiamidos** [comment]
try with this
             ```
             <Header>
                 <Left style={{flex:1}}>
                <Button transparent    >
                  <Icon name="arrow-back" onPress={() => this.props.navigation.goBack()}/>
                </Button>
              </Left>
              <Body style={{flex:1,alignItems:'center'}}>
                <Title style={{textAlign:'left'}}>   3دیوار</Title>
              </Body>
              <Right style={{flex:1}}>
                <Button transparent onPress={() => this.props.navigation.navigate("DrawerOpen")}>
                  <Icon name="menu" />
                </Button>
              </Right> 
            </Header>

```
