### ISSUE TITLE
[Bug] Toast is not working within a Modal

### ISSUE THREAD

**Issue by JLLLinn** [GeekyAnts/NativeBase#985]
## react-native, react and native-base version
RN: 0.45.1
React:16.0.0-alpha.12
native-base: 2.1.5
## Expected behaviour
Toast to be shown in react native Modal
## Actual behaviour
The toast is not shown in react native Modal
## Steps to reproduce (code snippet or screenshot)
Do Toast.show() in a Modal
## Is the bug present in both ios and android or in any one of them?
No that I know of. This was working with RN on 0.44 and native-base on a lower version (I can't remember exactly which one, either 2.1.4 or 2.1.3)

**Comment by shivrajkumar** [comment]
@JLLLinn Check the latest of NativeBase i.e, v2.2.0

**Comment by laxgoalie392** [comment]
Was this verified that it was fixed? I think I'm experiencing it as well. My issue is that the Modal is covering the Toast so it isn't visible.

I'm on RN 0.46.4 and native base 2.2.1 and using the ios emulator.

Thanks!

**Comment by vovanmozg** [comment]
Same problem. I'm on RN 0.46.1 and native base 2.2.1 and using the ios emulator.

**Comment by mdebo** [comment]
Exactly the same problem using RN 0.47 and NativeBase 2.2.1.
Any news about it?
thanks!

**Comment by gianpaj** [comment]
The **Toast** still appears to me behind the **Modal** (from React Native):

![toast behind modal](https://media.giphy.com/media/xUOxfoxIwi2nBcyc00/giphy.gif)

the code is basically this:
```js
import React from 'react';
import {
  Modal,
  Toast,
  Text,
  View,
} from 'react-native';

export default class LoginScreen extends React.Component<Props, State> {
  state = {
    modalVisible: false,
  }

  onResetPassword() {
    Toast.show({
      text: message,
      duration: 2000,
      position: "top",
      textStyle: { textAlign: "center" },
    });
  }    

  render() {
    return (
      <View>
        <Modal
          animationType="slide"
          transparent={false}
          visible={this.state.modalVisible}
          >
          <View>...</View>
        </Modal>
      </View>
    )
  }
}
```

Any suggestions?

I see there's something called [zIndex](http://facebook.github.io/react-native/docs/layout-props.html#zindex) as Layout Props - React Native

Using:
```
$ yarn list --depth=0 | grep 'native-base@\| react-native@'
├─ native-base@2.3.3
├─ react-native@0.50.3
```

Can something be done to the ToastContainer.js?
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/ToastContainer.js

**Comment by SupriyaKalghatgi** [comment]
@gianpaj Looks like you are using React-Native-Seed boilerplate. Nice!
We will check this issue

**Comment by idrakimuhamad** [comment]
I just want to add that I’m having this issue too with v 2.3.3

**Comment by gianpaj** [comment]
FYI: this issue happens both on Android and iOS

**Comment by supercamilo** [comment]
Still present on 2.3.5

**Comment by gianpaj** [comment]
I think I'm just going to use the `Toast` from [ant-design-mobile](https://github.com/ant-design/ant-design-mobile):

```
import { Toast } from 'antd-mobile';
```

They seem to be more consistent with the development and maintenance of the library:
https://github.com/ant-design/ant-design-mobile/graphs/commit-activity
https://github.com/GeekyAnts/NativeBase/graphs/commit-activity

OT: For the contributors, maybe think of using gitcoin.co or patreon.com if you need some $$ incentive to keep this project going and put more resources. I'll be happy to chip in and help the project

**Comment by idrakimuhamad** [comment]
@gianpaj I'm also using antd-mobile for the datepicker. Perhaps I should take a look at their toast implementation too.

**Comment by ThomasLabstep** [comment]
Any hotfix for now with v2.3.10 ?

**Comment by AdrianMrn** [comment]
Any chance this will be fixed anytime soon?

**Comment by Zeratyll** [comment]
Сталкивался с этой проблемой недавно, решил следующим способом. Просто добавляем в Modal элемент Root, а в него весь контент который вам нужен

P.S. на английский переводить лень, главное ведь код

`import { Root, Container, Content } from 'native-base';

<Modal>
<Root>
// .. modal content with toast
</Root>
</Modal>
`

**Comment by doreentseng** [comment]
@Zeratyll Hey! It doesn't work for me at all, the toast still appears behind the Modal.

**Comment by michaellee8** [comment]
@doreentseng Tried @Zeratyll 's solution of putting `<Root/>` into `<Modal/>`, but it still didn't work. 
@gianpaj  Also tried to put `style : { zIndex: 1000 }` into `Toast.show()`, no effect as well.
All of the results are tested in a real iPad.
@SupriyaKalghatgi @shivrajkumar Dear collaborators, when can we get an fix?

**Comment by akhil-geekyants** [comment]
checked this issue after merging PR https://github.com/GeekyAnts/NativeBase/pull/1700. Placing Root inside a modal component as suggested by @Zeratyll https://github.com/GeekyAnts/NativeBase/issues/985#issuecomment-383596951 is working fine after merging. See attached Gif.

Sample code
```
import React from 'react';
import { Modal } from "react-native";
import { createStackNavigator } from 'react-navigation';
import { Root, Container, Text, Header, Left, Body, Right, Title, Content, Button, Toast } from 'native-base';

class HomeScreen extends React.Component {

  state = { modalVisible: false }

  render() {
    return (
      <Container>
        <Header>
          <Left />
          <Body>
            <Title>Home screen</Title>
          </Body>
          <Right />
        </Header>

        <Content>
          <Button onPress={() => this.setState({ modalVisible: !this.state.modalVisible })} style={{ margin: 20 }}>
            <Text>Show modal</Text>
          </Button>
        </Content>

        <Modal
          animationType="slide"
          transparent={false}
          visible={this.state.modalVisible}>
          <Root>
            <Container style={{ padding: 20 }}>
              <Button style={{ margin: 20 }} onPress={() => Toast.show({
                text: 'Wrong password!',
                buttonText: 'Okay'
              })}>
                <Text>Show toast</Text>
              </Button>
              <Button style={{ margin: 20 }} onPress={() => this.setState({ modalVisible: !this.state.modalVisible })}>
                <Text>Hide modal</Text>
              </Button>
            </Container>
          </Root>
        </Modal>
      </Container>
    );
  }
}

const App = createStackNavigator({
  Home: {
    screen: HomeScreen
  },
}, {
    navigationOptions: {
      header: null
    }
  });

export default () => <Root>
  <App />
</Root>
``` 
Gif

![toast-modal](https://user-images.githubusercontent.com/27768184/41650536-e4aef4c8-749b-11e8-8d28-a77c9a3a99f7.gif)

**Comment by gianpaj** [comment]
> Placing Root inside a modal component as suggested ... is working fine
@akhil-geekyants 

This is not ideal or neither practical.

The state of Modal(s) should not be at the Root of an application. It should where the Modal should appear, i.e. inside a screen/component/container.

If we had to do the way you suggest, you would have to pass the Modal state all the way down to the Component in need (via props or in order ways).

I have to say this is not a viable option for any decent size application.

I don't know at the moment how to solve this, but pretty sure that's not it. Happy to be corrected if I'm wrong.

**Comment by akhil-geekyants** [comment]
@gianpaj updated my comment.

**Comment by JeremyBradshaw7** [comment]
Also having this problem. The <Root> workaround does work but also has an unwanted side-effect that non-fullscreen modals no longer appear vertically centered.

**Comment by lewisflude** [comment]
The above Root fix didn't work for me as I'd like it to, as it completely ruins the vertical centring of the Toast

**Comment by Aleksandern** [comment]
My workaround for modals.

scene.js
```
<Scene>
  <ModalComponent />
</Scene>
```

ModalComponent.js
```
import Toast from 'mypathto/Toast';
class ModalComponent Component {
  
    showToast() {
        Toast.show({
          text: 'modal toast',
          position: 'bottom',
          duration: 3000
        });
    }

    render() {
        return (
            <Modal>
                <View>
                    <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>

                    <Toast
                      ref={c => {
                        if (c) Toast.toastInstance = c;
                      }}
                    />

                </View>
            </Modal>
        )
    }
}
```

mypathto/Toast.js
```
import {
  Toast as ToastNB,
} from "native-base";

class Toast extends ToastNB {
}

export default Toast;
```

**Comment by tmtung144** [comment]
> Сталкивался с этой проблемой недавно, решил следующим способом. Просто добавляем в Modal элемент Root, а в него весь контент который вам нужен
> 
> P.S. на английский переводить лень, главное ведь код
> 
> translation : Faced this problem recently, I decided in the following way. Just add the Root element to the Modal, and all the content you need is in it
> 
> ```
> import { Root, Container, Content } from 'native-base';
> 
> <Modal>
>     <Root>
>         <Container>
>              <Content>
>                   // .. modal content with toast
>              </Content>
>         </Container>
>     </Root>
> </Modal>
> ```

Very good, it works with me

**Comment by AonanLi** [comment]
> My workaround for modals.
> 
> scene.js
> 
> ```
> <Scene>
>   <ModalComponent />
> </Scene>
> ```
> ModalComponent.js
> 
> ```
> import Toast from 'mypathto/Toast';
> class ModalComponent Component {
>   
>     showToast() {
>         Toast.show({
>           text: 'modal toast',
>           position: 'bottom',
>           duration: 3000
>         });
>     }
> 
>     render() {
>         return (
>             <Modal>
>                 <View>
>                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> 
>                     <Toast
>                       ref={c => {
>                         if (c) Toast.toastInstance = c;
>                       }}
>                     />
> 
>                 </View>
>             </Modal>
>         )
>     }
> }
> ```
> mypathto/Toast.js
> 
> ```
> import {
>   Toast as ToastNB,
> } from "native-base";
> 
> class Toast extends ToastNB {
> }
> 
> export default Toast;
> ```

Works for me, Nice Solution

**Comment by manojeeva** [comment]
@

> > My workaround for modals.
> > scene.js
> > ```
> > <Scene>
> >   <ModalComponent />
> > </Scene>
> > ```
> > ModalComponent.js
> > ```
> > import Toast from 'mypathto/Toast';
> > class ModalComponent Component {
> >   
> >     showToast() {
> >         Toast.show({
> >           text: 'modal toast',
> >           position: 'bottom',
> >           duration: 3000
> >         });
> >     }
> > 
> >     render() {
> >         return (
> >             <Modal>
> >                 <View>
> >                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> > 
> >                     <Toast
> >                       ref={c => {
> >                         if (c) Toast.toastInstance = c;
> >                       }}
> >                     />
> > 
> >                 </View>
> >             </Modal>
> >         )
> >     }
> > }
> > ```
> > mypathto/Toast.js
> > ```
> > import {
> >   Toast as ToastNB,
> > } from "native-base";
> > 
> > class Toast extends ToastNB {
> > }
> > 
> > export default Toast;
> > ```
> 
> Works for me, Nice Solution

This works fine for modal.
After I try to show normal toast without modal. showToast is not a function.  I can't find any ref related to Toast instance from Root component

**Comment by filippoitaliano** [comment]
> 
> 
> My workaround for modals.
> 
> scene.js
> 
> ```
> <Scene>
>   <ModalComponent />
> </Scene>
> ```
> 
> ModalComponent.js
> 
> ```
> import Toast from 'mypathto/Toast';
> class ModalComponent Component {
>   
>     showToast() {
>         Toast.show({
>           text: 'modal toast',
>           position: 'bottom',
>           duration: 3000
>         });
>     }
> 
>     render() {
>         return (
>             <Modal>
>                 <View>
>                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> 
>                     <Toast
>                       ref={c => {
>                         if (c) Toast.toastInstance = c;
>                       }}
>                     />
> 
>                 </View>
>             </Modal>
>         )
>     }
> }
> ```
> 
> mypathto/Toast.js
> 
> ```
> import {
>   Toast as ToastNB,
> } from "native-base";
> 
> class Toast extends ToastNB {
> }
> 
> export default Toast;
> ```

It's necessary to extend the Toast? I tried the trick directly with NB export and it worked.

**Comment by jayan2019** [comment]
`onPress={()=>this.setState({ toastVisible: !this.state.toastVisible },() =>Toast.show({ text: 'Wrong password!', buttonText: 'Okay' }))}`

This code is working for me. Thanks @akhil-geekyants. This comment helped me
[https://github.com/GeekyAnts/NativeBase/issues/985#issuecomment-398688935](url)

**Comment by suvenduchhatoi** [comment]
As mentioned in NB Docs https://docs.nativebase.io/Components.html#toast-def-headref - `For Toast to work, you need to wrap your topmost component inside <Root> from native-base.` ,the solution is to wrap `Toast` with `Root` within `Modal`, which has already been found in discussion above...

**Comment by artshevtsov** [comment]
Wrapping modal content with <Root> solved the problem with z-indexing for me

**Comment by Jhony-Reyes** [comment]
In my case I use `Modal` as component and the `Toast` is being shown after executing an async function, this works for me:

Modal Component: 

```
import Toast from 'path/toast';

const ModalContainer = ({
  visible, onClose, children, onShow,
}) => (
  <Modal
    visible={visible}
    onRequestClose={onClose}
    onShow={() => onShow(Toast)}
  >
    <View>
      {children}
    </View>
    <Toast
      ref={(t) => {
        Toast.toastInstance = t;
      }}
    />
  </Modal>
);

```

Usign the Modal Component:

```
import ModalContainer from 'path/modalContainer/;

class SomeClass Component {
  
    showToast() {
       add1(10).then(() =>  this.toastInstance.show({
          text: 'modal toast',
          position: 'bottom',
          duration: 3000
        }));
    }

    render() {
        return (
         <ModalContainer onShow={(e) => { this.toastInstance = e; }}>
              <Text>Hi</Text>
         </ModalContainer>
        )
    }
}
```

**Comment by summerkiflain** [comment]
Why can't we add `containerStyle` to `Toast.show()` mothod? all of above solutions seem very unnecessary.

**Comment by CyberCyclone** [comment]
I think a better solution is to define which component the Toast appears in. Or is it assumed that the top most <Root> is the one that it's attached to?

**Comment by cristianoccazinsp** [comment]
Please re-open this.

Putting a <Root> component inside <Modal> does work; however, if you ever try to show another toast (let's say you had a root in your main - non-modal - component), then trying to show another toast will horribly crash because the <root> instance will no longer be available.

**Comment by HeyShinner** [comment]
> My workaround for modals.
> 
> scene.js
> 
> ```
> <Scene>
>   <ModalComponent />
> </Scene>
> ```
> 
> ModalComponent.js
> 
> ```
> import Toast from 'mypathto/Toast';
> class ModalComponent Component {
>   
>     showToast() {
>         Toast.show({
>           text: 'modal toast',
>           position: 'bottom',
>           duration: 3000
>         });
>     }
> 
>     render() {
>         return (
>             <Modal>
>                 <View>
>                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> 
>                     <Toast
>                       ref={c => {
>                         if (c) Toast.toastInstance = c;
>                       }}
>                     />
> 
>                 </View>
>             </Modal>
>         )
>     }
> }
> ```
> 
> mypathto/Toast.js
> 
> ```
> import {
>   Toast as ToastNB,
> } from "native-base";
> 
> class Toast extends ToastNB {
> }
> 
> export default Toast;
> ```

Actually it works for me,
but Toast should display on the top of the Login page instead of the top of the config Modal: 

![image](https://user-images.githubusercontent.com/16172530/78128116-f62f0c80-7447-11ea-91aa-3e838dbb78df.png)

This is My  code:

![image](https://user-images.githubusercontent.com/16172530/78128500-a13fc600-7448-11ea-8f19-c42f6faf1edd.png)

**Comment by Aryk** [comment]
I tried using this but ran into an issue on react-navigation.

If you click to a page, and then click back...the re-render won't trigger and the ref won't get reset and then you'll get the null toastInstance error. 

So, I needed to add a useFocusEffect to reset the instance when it comes back to that screen.

Here is my solution based on the one below...so far seems to be working. Also, I'm not using "Modal", but using instead transparentModal and normal screens in the StackNavigator from react-native-screens but same issue....

```tsx

// Solution based on the one here: https://github.com/GeekyAnts/NativeBase/issues/985#issuecomment-411379940
import {Container as ContainerNB, NativeBase, Toast as ToastNB} from "native-base";
import {useFocusEffect} from "@react-navigation/native";

class Toast extends ToastNB {}

const Container = ({children, style, ...props}: NativeBase.Container & {children: any}) => {

  const toastInstance = useRef();

  useFocusEffect(useCallback(() => {
    if (toastInstance.current && toastInstance !== (Toast as any).toastInstance) {
      (Toast as any).toastInstance = toastInstance.current;
    }
  }, []));

  return <ContainerNB {...props}>
    {/*Needs to be first*/}
    {children}
    {/*// @ts-ignore*/}
    <Toast
      ref={c => {
        if (c) {
          (Toast as any).toastInstance = c;
          toastInstance.current = c;
        }
      }}
    />
  </ContainerNB>;
};
```

> My workaround for modals.
> 
> scene.js
> 
> ```
> <Scene>
>   <ModalComponent />
> </Scene>
> ```
> 
> ModalComponent.js
> 
> ```
> import Toast from 'mypathto/Toast';
> class ModalComponent Component {
>   
>     showToast() {
>         Toast.show({
>           text: 'modal toast',
>           position: 'bottom',
>           duration: 3000
>         });
>     }
> 
>     render() {
>         return (
>             <Modal>
>                 <View>
>                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> 
>                     <Toast
>                       ref={c => {
>                         if (c) Toast.toastInstance = c;
>                       }}
>                     />
> 
>                 </View>
>             </Modal>
>         )
>     }
> }
> ```
> 
> mypathto/Toast.js
> 
> ```
> import {
>   Toast as ToastNB,
> } from "native-base";
> 
> class Toast extends ToastNB {
> }
> 
> export default Toast;
> ```

**Comment by HeyShinner** [comment]
> I tried using this but ran into an issue on react-navigation.
> 
> If you click to a page, and then click back...the re-render won't trigger and the ref won't get reset and then you'll get the null toastInstance error.
> 
> So, I needed to add a useFocusEffect to reset the instance when it comes back to that screen.
> 
> Here is my solution based on the one below...so far seems to be working. Also, I'm not using "Modal", but using instead transparentModal and normal screens in the StackNavigator from react-native-screens but same issue....
> 
> ```tsx
> // Solution based on the one here: https://github.com/GeekyAnts/NativeBase/issues/985#issuecomment-411379940
> import {Container as ContainerNB, NativeBase, Toast as ToastNB} from "native-base";
> import {useFocusEffect} from "@react-navigation/native";
> 
> class Toast extends ToastNB {}
> 
> const Container = ({children, ...props}: NativeBase.Container & {children: any}) => {
> 
>   const toastInstance = useRef();
> 
>   useFocusEffect(useCallback(() => {
>     if (toastInstance.current && toastInstance !== (Toast as any).toastInstance) {
>       (Toast as any).toastInstance = toastInstance.current;
>     }
>   }, []));
> 
>   return <ContainerNB {...props}>
>     {/*Needs to be first*/}
>     {children}
>     {/*// @ts-ignore*/}
>     <Toast
>       ref={c => {
>         if (c) {
>           (Toast as any).toastInstance = c;
>           toastInstance.current = c;
>         }
>       }}
>     />
>   </ContainerNB>;
> };
> ```
> 
> > My workaround for modals.
> > scene.js
> > ```
> > <Scene>
> >   <ModalComponent />
> > </Scene>
> > ```
> > 
> > 
> > ModalComponent.js
> > ```
> > import Toast from 'mypathto/Toast';
> > class ModalComponent Component {
> >   
> >     showToast() {
> >         Toast.show({
> >           text: 'modal toast',
> >           position: 'bottom',
> >           duration: 3000
> >         });
> >     }
> > 
> >     render() {
> >         return (
> >             <Modal>
> >                 <View>
> >                     <Button onPress={()=>this.showToast()}><Text>Toast<Text></Button>
> > 
> >                     <Toast
> >                       ref={c => {
> >                         if (c) Toast.toastInstance = c;
> >                       }}
> >                     />
> > 
> >                 </View>
> >             </Modal>
> >         )
> >     }
> > }
> > ```
> > 
> > 
> > mypathto/Toast.js
> > ```
> > import {
> >   Toast as ToastNB,
> > } from "native-base";
> > 
> > class Toast extends ToastNB {
> > }
> > 
> > export default Toast;
> > ```

Got it! I will give my feedback after I try this nice solution!

**Comment by Rc85** [comment]
> As mentioned in NB Docs https://docs.nativebase.io/Components.html#toast-def-headref - `For Toast to work, you need to wrap your topmost component inside <Root> from native-base.` ,the solution is to wrap `Toast` with `Root` within `Modal`, which has already been found in discussion above...

I can confirm what @cristianoccazinsp is true. The instance is no longer available after the Toast in Modal hides.

```
null is not an object (evaluating
'this.toastInstance.root.showToast')
```

**Comment by emil-keyvalue** [comment]
@SupriyaKalghatgi The issue is still not solved. Why haven't you added support for multiple roots yet

**Comment by denven** [comment]
I find this exists in 2021, I just get it shown up via adding a delay to show it:
```
         setTimeout(() => Toast.show('Your message here') , 500);
```

**Comment by dexterowy** [comment]
After 4 years toast still appears under the modal. Also, `Root` component was removed. Could you fix that?

**Comment by garrett-gottlieb** [comment]
This should be reopened

**Comment by amitdninawe** [comment]
I got a Hack, adding blank <Toast />  inside the modal code works. I have tested this in android only. Please give it a shot and let me know.

![image](https://user-images.githubusercontent.com/84501226/148758091-1da8fd84-3759-4bf0-9a7a-84b456444f52.png)

**Comment by rs6g10** [comment]
Neither `<Toast />` nor `Root` exist as components in version `3.2.2`. There aren't any better workarounds for this. Can we get this issue reopened please?

**Comment by rs6g10** [comment]
Since `Root` no longer exists, a quick workaround is wrapping the entire `Modal` content in `NativeBaseProvider`.

I'm using the following workaround for version `3.2.2` to see toasts in my `react-native-modal`:
```jsx
<RNModal
   isVisible={modalVisible}
   deviceWidth={deviceWidth}
   deviceHeight={deviceHeight}
   coverScreen={true}
   style={styles.modal}
    >
      <NativeBaseProvider>
        <View style={styles.modalHeader}>
          <TouchableOpacity
            style={{ marginTop: 48 }}
          >
            <Icon
              name='close'
              as={MaterialCommunityIcons}
              onPress={onClose}
              size={12}
              style={{
                right: 16,
                alignSelf: 'flex-end',
              }}
            />
          </TouchableOpacity>
          <View style={styles.modalBody}>
            {children}
          </View>
        </View>
      </NativeBaseProvider>
</RNModal>
```

**Comment by MD-REHMAN** [comment]
I'm reopening this issue, and we'll keep it on high priority.

**Comment by Drakeoon** [comment]
@MD-REHMAN I would also love this feature to be back, ideally a separate API to configure Toast root element.

Have you guys started working on it already? I would love to help or take care of that issue, so that we can have it back on our project 💪🏻

**Comment by masrurimz** [comment]
> Since `Root` no longer exists, a quick workaround is wrapping the entire `Modal` content in `NativeBaseProvider`.
> 
> I'm using the following workaround for version `3.2.2` to see toasts in my `react-native-modal`:
> 
> ```js
> <RNModal
>    isVisible={modalVisible}
>    deviceWidth={deviceWidth}
>    deviceHeight={deviceHeight}
>    coverScreen={true}
>    style={styles.modal}
>     >
>       <NativeBaseProvider>
>         <View style={styles.modalHeader}>
>           <TouchableOpacity
>             style={{ marginTop: 48 }}
>           >
>             <Icon
>               name='close'
>               as={MaterialCommunityIcons}
>               onPress={onClose}
>               size={12}
>               style={{
>                 right: 16,
>                 alignSelf: 'flex-end',
>               }}
>             />
>           </TouchableOpacity>
>           <View style={styles.modalBody}>
>             {children}
>           </View>
>         </View>
>       </NativeBaseProvider>
> </RNModal>
> ```

Could you provide example to customize native base modal, action sheet and other overlay component so, toast will be appeared on the top of it

**Comment by Oct4Pie** [comment]
I have the same issue. The toast doesn’t appear on the modal. No solutions yet.

**Comment by iooi** [comment]
+1

**Comment by zzyjiaxinmomo** [comment]
is there any solution now?

**Comment by Viraj-10** [comment]
Hi @zzyjiaxinmomo @iooi @Oct4Pie, Can you provide small snack example ?

**Comment by Oct4Pie** [comment]
> Hi @zzyjiaxinmomo @iooi @Oct4Pie, Can you provide small snack example ?

Hello, @Viraj-10. Here it is:
```jsx
import React from "react";
import {
  Text,
  HStack,
  Center,
  Switch,
  useColorMode,
  NativeBaseProvider,
  extendTheme,
  VStack,
  Modal,
  Input,
  FormControl,
  Button,
  useToast,
} from "native-base";

const config = {
  useSystemColorMode: false,
  initialColorMode: "dark",
};

export const theme = extendTheme({ config });

export default function App() {
  const [show, setShow] = React.useState(false);
  const toast = useToast();

  return (
    <NativeBaseProvider>
      <Center
        _dark={{ bg: "blueGray.900" }}
        _light={{ bg: "blueGray.50" }}
        px={4}
        flex={1}
      >
        <VStack space='3' >
          <Modal onClose={() => setShow(false)} isOpen={show}>
            <Modal.Content>
              <Modal.CloseButton />
              <Modal.Header>Sign In</Modal.Header>
              <Modal.Body>
                Please enter your credentials to proceed
                <FormControl mt={{
                  'base': '3',
                  'lg': '4',
                  '2xl': '5',
                }}>
                  <FormControl.Label>Email</FormControl.Label>
                  <Input />
                </FormControl>
                <FormControl mt={{
                  'base': '3',
                  'lg': '4',
                  '2xl': '5',
                }}>
                  <FormControl.Label>Password</FormControl.Label>
                  <Input />
                </FormControl>
              </Modal.Body>
              <Modal.Footer>
                <Button onPress={() => {
                  toast.show({
                    // variant: "solid",
                    description: "You are signed in!",
                  })
                  // setShow(false);
                }}>
                  Sign In
                </Button>
              </Modal.Footer>
            </Modal.Content>
          </Modal>
          <VStack space={8} alignItems="center">
            <Button w="104" onPress={() => {
              setShow(!show);
            }}>
              Sign In Modal
            </Button>
          </VStack>
          <ToggleDarkMode />
        </VStack>
        <SignInModal />

      </Center>
    </NativeBaseProvider>
  );
}

const SignInModal = () => {
  const [show, setShow] = React.useState(false);
  const toast = useToast();
  return <VStack space='3' >

    <Modal onClose={() => setShow(false)} isOpen={show}>
      <Modal.Content>
        <Modal.CloseButton />
        <Modal.Header>Sign In</Modal.Header>
        <Modal.Body>
          Please enter your credentials to proceed
          <FormControl mt={{
            'base': '3',
            'lg': '4',
            '2xl': '5',
          }}>
            <FormControl.Label>Email</FormControl.Label>
            <Input />
          </FormControl>
          <FormControl mt={{
            'base': '3',
            'lg': '4',
            '2xl': '5',
          }}>
            <FormControl.Label>Password</FormControl.Label>
            <Input />
          </FormControl>
        </Modal.Body>
        <Modal.Footer>
          <Button onPress={() => {
            toast.show({
              variant: "solid",
              description: "You are signed in!",
            })
            // setShow(false);
          }}>
            Sign In
          </Button>
        </Modal.Footer>
      </Modal.Content>
    </Modal>
    <VStack space={8} alignItems="center">
      <Button onPress={() => {
        setShow(!show);
      }}>
        Sign In Modal (component)
      </Button>
    </VStack>
  </VStack>;
}

function ToggleDarkMode() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <HStack space={2} alignItems="center">
      <Text>Dark</Text>
      <Switch
        isChecked={colorMode === "light"}
        onToggle={toggleColorMode}
        aria-label={
          colorMode === "light" ? "switch to dark mode" : "switch to light mode"
        }
      />
      <Text>Light</Text>
    </HStack>
  );
}
```

As you can see, `useToast` does not work in the `default` App function. I need the modal to be in `App` since the state variables must be passed to other screens. I couldn't find a way to solve this issue and wrote a similar component to toast, but it's not as efficient.

**Comment by Viraj-10** [comment]
Hi All, Let me explain what's going on internally. 
On Android, we use `RN Modal` and on IOS we use Overlay Component which is View with `absoluteFill` Styling. 
Since IOS doesn't support multiple Modal we have to render an Overlay. 
Now, whenever you render `RN modal` on android it mounts on top of the application but toast is again an overlay. So it renders below `RN Modal`. 
Solution
Complete remove RN Modal and use Overlay instead. (Difficulties Accessibility).

**Comment by danimayfield** [comment]
Is there any solution to this yet?

**Comment by bilalalbkre** [comment]
the solution worked in my case 
[](https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md)
just add <Toast /> inside the Modal

**Comment by bilalalbkre** [comment]
the solution worked in my case
https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md
just add inside the Modal

**Comment by bilalalbkre** [comment]
that solution worked in my case
https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md
just add "Toast" tag inside the Modal component

**Comment by sturmenta** [comment]
> **"useRNModalOnAndroid: false", default for component "Modal" helped**
> 
> ```
> const theme = extendTheme({
>   components: {
>     Modal: {
>       defaultProps: {
>         _overlay: {
>           useRNModalOnAndroid: false,
>         },
>       },
>     },
>   }
> });
> ```

your initial problem was in android or iOS?

**Comment by Aryk** [comment]
In short, no...they slowly (and quietly) moved on to another project  - https://ui.gluestack.io/

**Comment by levon-zakarian** [comment]
After trying everything here and with no luck, I still kept struggling with this for a long time, and after checking how Toast works multiple times I've come across a workaround that finally worked for me.

So under the hood it is using `useContext` and there is a Provider that is also exported in `native-base` called `ToastProvider`, and when you use it _Inside_ the Modal it works as expected.

Here's a sample code:

Container.tsx

```typescript
import { useState } from "react";

// components
import { Button, Center, VStack, useToast } from "native-base";
import ModalToast from "./ModalToast";

const Container = () => {
  const toast = useToast();
  const [isOpen, setIsOpen] = useState(false);

  const closeModal = () => {
    setIsOpen(false);
  };

  const openModal = () => {
    setIsOpen(true);
  };

  const showToast = () => {
    toast.show({ title: "A Regular Toast In App" });
  };

  return (
    <Center flex={1}>
      <VStack space={5}>
        <Button onPress={openModal}>Open Modal</Button>
        <Button onPress={showToast}>Show Outer Toast</Button>
      </VStack>

      <ModalToast isOpen={isOpen} onClose={closeModal} />
    </Center>
  );
};

export default Container;

``` 

ModalToast.tsx

```typescript
import {
  Button,
  Center,
  HStack,
  Modal,
  ToastProvider,
  useToast,
} from "native-base";

const ModalContent = ({ onClose }: { onClose: () => void }) => {
  const toast = useToast();

  const showToast = () => {
    toast.show({ title: "A Toast over the modal" });
  };

  return (
    <Center flex={1}>
      <HStack space={4}>
        <Button onPress={showToast}>Show Toast</Button>
        <Button onPress={onClose}>Close Modal</Button>
      </HStack>
    </Center>
  );
};

interface ModalToastProps {
  isOpen: boolean;
  onClose: () => void;
}

const ModalToast = ({ isOpen, onClose }: ModalToastProps) => (
  <Modal
    isOpen={isOpen}
    animationPreset="slide"
    bg="gray.200"
    onClose={onClose}
    safeAreaBottom
  >
    <ToastProvider>
      <ModalContent onClose={onClose} />
    </ToastProvider>
  </Modal>
);

export default ModalToast;

``` 

The only issue is that the App toast still stays under the modal, as the one inside the modal is another provider so it displays whole other Toast.

https://github.com/GeekyAnts/NativeBase/assets/86891301/7af924fd-6ff1-4d2a-8315-b2ba122b98a9

Using both `Modal` & `Toast` from `native-base` `v3.4.28`

Hope this will be of help.

**Comment by jnariai** [comment]
A possible workaround is disabling overlay:
```tsx
      <Modal
        overlayVisible={false}
      >
 ```

**Comment by soemarko** [comment]
I mean, realistically, NativeBase is abandoned. I've just moved all Toast to [react-native-toast-message](https://github.com/calintamas/react-native-toast-message/). Bit by bit, I'm slowly removing native-base from my project.

I'll never go to gluestack if this how they handle projects. They'll abandon gluestack too as soon as a new shiny thing coming down the line.

**Comment by iooi** [comment]
Can we get the refund?

**Comment by LordAsmodey** [comment]
I have my own separate context provider for toasters, which wraps the parts of my application I need. And as I see, everything now works as it should on iOS devices. And for Android, the setup that [astaninivan1](https://github.com/astaninivan1) suggested helped me.
https://github.com/GeekyAnts/NativeBase/issues/985#issuecomment-1511680753
But the fact that the NB has not been updated for a year makes me sad...
